catppuccin/userstyles

src/generate/generate.ts
src/generate/types.d.ts
src/userstyles.schema.json

The validate function that ajv generates has type predicates to narrow the type automatically
> compiled validation functions are type guards that narrow the type after successful validation.
[ajv TypeScript docs](https://ajv.js.org/guide/typescript.html)
https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

fix(generate): use type predicates from ajv instead of manual type annotations and fix localCompare usage

---

src/userstyles.yml

YT theme v2.0.0 was based of artilate YT port, however this is no longer the case.

fix: artilate not a maintainer

---

styles/wikiwand/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/97

fix(wikiwand): makes it apply and tables

---

styles/twitch/catppuccin.user.css

It gave the error "Invalid JSON: frappe is not a valid JSON literal" because of a missing quotation mark.

fix(twitch): Fix darkTheme json

---

.github/workflows/typos.yml
.typos.toml

This is mainly to enforce `en_US` spelling in this repository, and might also be useful to catch some syntax/className errors (e.g. the YouTube port with the current failure)

ci: add crate-ci/typos

---

styles/proton/catppuccin.user.css

fix(proton): email item text color on hover

---

.typos.toml
styles/chess.com/catppuccin.user.css
styles/deepl/catppuccin.user.css
styles/ecosia/catppuccin.user.css
styles/homepage/catppuccin.user.css
styles/lastfm/catppuccin.user.css
styles/paste.rs/catppuccin.user.css
styles/youtube/catppuccin.user.css

Corrections for all typos show in https://github.com/catppuccin/userstyles/actions/runs/5642097101
~Exclusion for the `tranpart` one from the youtube port.~
I checked the one from deepl and that appears to not be an issue.
@nekowinston, @sgoudham I know you both are interested/invested in this.

fix: correct the typos

---

styles/proton/catppuccin.user.css

Hacky but it works
All color codes are uppercased as they have to match with the attribute values in the HTML, and since Prettier seems to randomly lowercase color codes, I had to add `prettier-ignore` to those lines.
Original:
Sapphire:
Red:

feat(proton): accent-colored logos

---

styles/mastodon/catppuccin.user.css
styles/modrinth/catppuccin.user.css

The updateURL for mastodon's userstyle links to an invalid resource. It was just missing `styles/` directory.

fix invalid @updateURLs

---

styles/mastodon/catppuccin.user.css

As pointed in the [ctp discord](https://discord.com/channels/907385605422448742/1012720591180152893/1139802518168277063) the search popout was not being themed this fixes that issue.

fix(mastodon): search popout themeing

---

styles/github/catppuccin.user.css

- Changed the History button to better fit into the theme
- Fixed msising notification background on archived notifications
- Fixed missing sidebar button UI changes on fullscreen file explorer
- Fixed missing UI on "Add File" menu
- Fixed attached top bar when scrolling in the file explorer
- I think more too but I dont remember anymore

fix(github) - Fixed a lot of missing UI changes and adjusted some existing changes

---

styles/mastodon/catppuccin.user.css

the colors of the headerbar did looked off on the mobile view when compared to other apps with catppuccin. this commit aims to fix it

edit colors to better fit the catppuccin color scheme guides

---

styles/mastodon/catppuccin.user.css

This PR aims to add even more improvements and fixes to the mastodon theme

Improvements to mastodon's coloring

---

styles/chatgpt/catppuccin.user.css

Use catppuccin/highlightjs for the codeblocks. (With one minor change to match the code background and the container background)

feat(chatgpt): highlightjs

---

styles/chatgpt/catppuccin.user.css

This uses and `@import` to bring in https://unpkg.com/@catppuccin/highlightjs@0.1.2/css/catppuccin.variables.css
This should allow for easier updates based on the CTP releases
Example:

feat(chatgpt): use highlightjs import

---

.github/workflows/generate.yml

This commit adds a new job to call the readme workflow within the main catppuccin/catppuccin repository. This will make sure that any additions to userstyles will be synced with the README on the main repository.
> [!NOTE]
> This should not be merged until [`readme.yaml`](https://github.com/catppuccin/catppuccin/blob/main/.github/workflows/readme.yml) is turned into a re-usable workflow.

ci: call `readme.yml` in `catppuccin/catppuccin`

---

styles/vercel/catppuccin.user.css

fix(vercel): landing card grid gradient

---

docs/CONTRIBUTING.md

Add info regarding updating the version number of the userstyle in order for it to be pushed as a new update to users without requiring a reinstall.

docs: add version info to general recommendations

---

src/userstyles.yml
styles/hoppscotch/assets/catwalk.webp
styles/hoppscotch/assets/frappe.webp
styles/hoppscotch/assets/latte.webp
styles/hoppscotch/assets/macchiato.webp
styles/hoppscotch/assets/mocha.webp
styles/hoppscotch/catppuccin.user.css

Added hoppscotch to the userstyles :)
template.

feat: add hoppscotch

---

styles/mastodon/catppuccin.user.css

Fixing an issue where the profile header was partially hidden due to a styled div on top.
Before: 
After:

fix(mastodon): overlaying profile header

---

styles/youtube/catppuccin.user.css

<details>
<summary>Screenshot of original github theme for reference</summary>
</details>
<details>
<summary>Screenshot of catppuccin theme before this PR</summary>
</details>
<details>
<summary>Screenshot of catppuccin theme after this PR</summary>
</details>
Or maybe I ditched the wrong color? Maybe these icons should be more contrast but I made them as on screenshot due to this icon being not contrast enough either:
<details>
<summary>Screeshot of top left corner burger icon</summary>
</details>
Please review my PR carefully because I am not really into custom website themes and for me they look like just a huge mess :D

fix(youtube): match colors of topbar menu icons

---

styles/brave-search/catppuccin.user.css

I'll assume that this isn't intended as it does look a little weird. It seems like an oversight, or something Brave may have added since this was released:
With Style installed as is there is a weird gradient within the search-bar. That is fixed via this PR.
Before / After

Brave Search – remove searchbar background gradient

---

README.md
styles/chatgpt/catppuccin.user.css

this fixes the following issue:
**Before:**
**After:**

fix(chatgpt): boxes color and highlighting

---

styles/github/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/231

fix(github): move warning to the left so that users can still access settings and signin

---

styles/searxng/catppuccin.user.css

fix(searxng): improve metadata readability

---

src/userstyles.yml
styles/github/catppuccin.user.css

This commit aims to clearly highlight that the GitHub default theme should be changed via the Appearance settings.
**Are we able to include links in this content?** It would be nice to maybe link to the GitHub docs as that will be updated regularly updated by GitHub themselves.

docs(github): mention GitHub appearance settings

---

src/userstyles.yml

"for the Catppuccin GitHub userstyle theme for the best experience" doesn't really make sense.

docs(github): fix readme grammar

---

styles/syncthing/catppuccin.user.css

As discussed on discord, using the old regex that will capture any url with the specified port can be extremely leaky and will not work if someone has 2 urls with 2 different ports.
This PR attempts to fix that by replacing the port option with a setting to specify urls separated with commas.
Now one has to specify urls like `127\.0\.0\.1\:8384,localhost\:8384`
`127\.0\.0\.1\:8384,localhost\:8384` is the default setting.

fix(syncthing): replace leaky port capture with proper url config

---

docs/browsers.md

This PR updates `docs/browsers.md` to use the new GitHub callout syntax, `[!NOTE]` (sorry I missed this file earlier!) and corrects the syntax for the browsers table.

docs: update browsers.md

---

.github/workflows/file-checker.yml
.github/workflows/format.yml
.github/workflows/generate.yml
.github/workflows/issues.yml
.github/workflows/maintainers.yml
.github/workflows/pull-requests.yml
.github/workflows/sync-labels.yml
.github/workflows/typos.yml

I'm not sure why each step's name is title case - doesn't really fit with GitHub actions casing (see below), though I do understand title case workflow titles, happy to change that back. Otherwise, this PR bumps all uses of `actions/checkout` to `v4` and `stefanzweifel/git-auto-commit-action` to `v5`. I also removed the `commit_author` field used with `stefanzweifel/git-auto-commit-action` since it is already the default with the action.

ci: bump actions and make titles lowercase

---

styles/stylus/catppuccin.user.css

This PR adjusts the background color of the save button when disabled (which is when a userstyle hasn't been edited).
**Default Stylus**:
**Before**:
**Now**:
I just selected the `#save-button` for now but should this apply to all buttons?

fix(stylus): disabled button state

---

styles/deepl/catppuccin.user.css

This pull request addresses an issue where the `flex-shrink` property was incorrectly applied to elements when Zen mode is enabled, leading to unexpected layout shrinkage.
Commenting out the line `display: flex;` in `[data-testid="translator"]` seems to resolve this issue.

fix(deepl): flex-shrink in zen mode

---

styles/hacker-news/catppuccin.user.css
styles/invidious/catppuccin.user.css
styles/mastodon/catppuccin.user.css
styles/youtube/catppuccin.user.css

Changes how overriding `url("data:image/svg...")` is done across all styles, without base64-encoding it, and using `@{escaped-values}` to manipulate colors instead of `mask-image` etc.

refactor(treewide): `url("data:image/svg+xml,@{svg}")`

---

.github/PULL_REQUEST_TEMPLATE/userstyle-creation.md
.github/PULL_REQUEST_TEMPLATE/userstyle-update.md
.github/pull_request_template.md

I've seen @isabelroses comment about updating the version when someone fixes a userstyle a million times and I think it might help if we have a PR template checklist for that. Turns out GitHub doesn't have a pull request template picker (like the issue template picker) so you have to do this little workaround with query strings.

chore: add pull request template picker and userstyle update template

---

.github/workflows/pr-titles.yml

Adds a workflow to lint pull request titles against the conventional commit specification as discussed in Discord.
I'm using the example workflow they gave for adding a comment: https://github.com/marketplace/actions/semantic-pull-request#outputs. Thoughts? Should we just the workflow fail or is the comment good?

ci: add pull request title linter workflow

---

styles/youtube/catppuccin.user.css

fix(yt): private video warning

---

styles/github/catppuccin.user.css

fix(github): update regex to exclude `.patch` and `.diff` urls

---

.github/workflows/format.yml
.github/workflows/generate.yml
.github/workflows/issues.yml
.github/workflows/lint.yml
.github/workflows/maintainers.yml
.github/workflows/pr-titles.yml
.github/workflows/pull-requests.yml
.github/workflows/sync-labels.yml
.github/workflows/typos.yml

Just a few touchups so everything looks nice.

ci: cleanup workflows

---

styles/github/catppuccin.user.css

path styling and committer in the tree view
fork repo button and commit changes button
link on fork repo page
closes #304

fix(github): some fixes

---

scripts/lint/main.ts
scripts/lint/metadata.ts
scripts/usercss-meta.d.ts

Got tired of not having types for the usercss-meta library, so I added the ones we use (I'll need those again later anyways)
Oh and it also doesn't die on a single parse error in the metadata anymore so that's good

ci(lint): refactor & add type decl

---

scripts/lint/stylelint.ts

Stylus v1.5.35, which is the latest version on the Firefox add-on store, is unable to process e.g. `@media (width >= 35rem) {}` (context notation) when using less. `@media (min-width: 35rem) {}` (prefix notation) works fine.
This has been fixed in Stylus v1.5.37, which is not yet on the Firefox add-on store. However on the latest version (v1.5.38) other media queries still result in errors: e.g. `@media (not (display-mode: fullscreen)) {}` (the outer braces are needed when nesting in less, but are valid CSS), which might need further handling.
With the current set of rules the linter throws errors, when not using context notation.
For compatibility reasons we should prefer prefix notation.

ci(lint): set media-feature-range-notation to "prefix"

---

.typos.toml

For the `#analyse-cm` typo false positive in #346

ci(typos): also exclude id selectors

---

styles/gmail/catppuccin.user.css
styles/hacker-news/catppuccin.user.css
styles/skiff/catppuccin.user.css

As title says, no need to use `url-prefix("https://` if there isn't a path at the end - we should just use `domain()`.

fix: avoid extra url-prefix when possible

---

styles/chatgpt/catppuccin.user.css

Corrects a typo in a CSS variable. Kinda irrelevant since it (crust) isn't actually used in catppuccin/highlightjs but good to have correct I would think.
^ I don't think a version bump is necessary here lol.

fix(chatgpt): css variable typo

---

styles/stylus/catppuccin.user.css

fix(stylus): some color when opening the extension from tab or smth

---

styles/google/catppuccin.user.css

The google logo ain't colored in the "Images" tab unlike other tabs

fix(google): color logo in images tab

---

styles/reddit/catppuccin.user.css

fix(reddit): color the recap logo

---

styles/whatsapp-web/catppuccin.user.css

This splits the flavor variable into light and dark flavors that can be selected independently by the user. The rest of the usercss is also adjusted to change depending on the current WhatsApp Web theme.

feat(whatsapp): split flavor variable into light and dark

---

styles/youtube/catppuccin.user.css

annoying, the page does not have a dark version, so whatever theme the users set as light mode will be the colors used, blame youtube.
Youtube Error Page's Background

fix: youtube error page background

---

styles/proton/catppuccin.user.css

This splits the flavor variable into light and dark flavors for the Proton userstyle that can be selected independently by the user. It still requires that the user select the correct themes, as explained in the current readme.

feat(proton): split flavor variable into light and dark

---

styles/youtube/catppuccin.user.css

fix(youtube): search icon in result list

---

scripts/userstyles.yml

Tutanota has rebranded as Tuta, therefore we should reflect this change in the userstyles schema.
If you want to learn more about the change:  [https://tuta.com](https://tuta.com)

refactor: tutanota -> tuta

---

styles/nixos.wiki/catppuccin.user.css

Adds highlighting for diff codeblocks
Closes #388

fix(nixos.wiki): fix diff highlighting

---

styles/youtube/catppuccin.user.css

Fixes YouTube's Ambient Mode which was creating a weird background. As a solution, I've used `mix-blend-mode: lighten`.
Also removed a typo that was causing an error.

fix: youtube ambient mode + typo

---

styles/youtube/catppuccin.user.css

fix(youtube): sidebar icon colors broke after previous commit

---

styles/chatgpt/catppuccin.user.css

use crust on sidebar, since it was broken idk

fix(chatgpt): use crust on sidebar

---

scripts/sync-maintainers/main.ts

Add logging to the `sync-maintainers` script as @sgoudham suggested.

ci(sync-maintainers): add logging

---

styles/google/catppuccin.user.css

This splits the flavor variable into light and dark flavors that can be selected independently by the user.

feat(google): split flavor variable into light and dark

---

styles/whatsapp-web/catppuccin.user.css

When forwarding media, the text box and surrounding area were using the default colors.
They have been changed to match the theme to mantle for the background, and crust for the text box.

fix(whatsapp): caption when forwarding media

---

styles/hacker-news/catppuccin.user.css

This splits the flavor variable into light and dark flavors that can be selected independently by the user.

feat(hacker-news): split flavor variable into light and dark

---

styles/github/catppuccin.user.css

start using actively theming the contrib calander graph

fix(github): start actively theming the contribution calendar

---

styles/bsky/catppuccin.user.css

This PR adds theming for the "invalid handle" warning as well as the button for available invite codes in settings.

feat(bsky): theme some unthemed things

---

scripts/userstyles.yml

Having realised that we mainly get out icons from https://simpleicons.org/ it made sense to go there and compare icons it also allowed to quickly compare brand colors so now we have some more appropriate colors for some brands.

chore: update and cleanup icons and colors

---

styles/stylus/catppuccin.user.css

fix(stylus): make header color less deep to match text

---

styles/youtube/catppuccin.user.css

fix(youtube): change on sidebar icons coloring

---

scripts/userstyles.yml
styles/pinterest/catppuccin.user.css

I am not using Pinterest anymore, and I can't stand even seeing it really.
I am so sorry, but I'd like not to keep maintaining it from now on.
I am hoping that my latest rewrite will be more understandable if someone wants to take on.
I've also fixed some minor issues I've seen so far in this pull request.
Thank you <3
* Fixes the unthemed pin, profile pages and the flashlight button while not logged in.
* Fixes the white background in some containers like explore page.
* Color the Pinterest icons which have white outline.

refactor: remove jn-sena from pinterest

---

styles/youtube/catppuccin.user.css

fix(youtube): history tab title

---

styles/reddit/catppuccin.user.css

This has been bothering me ever since the userstyle was updated from Stylus to LESS, compare it

fix(reddit): border colors barely visible

---

styles/youtube/catppuccin.user.css

fix(youtube): button background when hovering is too light

---

styles/stylus/catppuccin.user.css

fix(stylus): userstyle settings header

---

styles/reddit/catppuccin.user.css

fix(reddit): post title when opened from notification

---

styles/instagram/catppuccin.user.css

fix: facebook stuff on log in page

---

styles/google/catppuccin.user.css

fix(google): color some more elements

---

styles/syncthing/catppuccin.user.css

Fixes the issue of being unable to specify more than two URLs because only the first comma got replaced in the document match regexp.

fix(syncthing): allow more than two URLs to be specified

---

styles/youtube/catppuccin.user.css

fix(youtube): color shorts logo triangle

---

scripts/lint/metadata.ts
scripts/utils.ts

Adds linting for the `@description` field. Clarifies a confusing unhandled error we got a little while back if a new userstyle `catppuccin.user.css` file is added but no section is added to `scripts/userstyles.yml`.

ci(lint): assert description, error on missing userstyle

---

styles/anilist/catppuccin.user.css
styles/bsky/catppuccin.user.css
styles/graphite/catppuccin.user.css
styles/hacker-news/catppuccin.user.css
styles/lingva/catppuccin.user.css
styles/proton/catppuccin.user.css
styles/skiff/catppuccin.user.css

Follow-up from #469, resolves lint issues discovered by the changes.

fix: match description field with userstyle branding

---

styles/gmail/catppuccin.user.css

The Gmail loading screen didn't have the correct colors, so I fixed it! :D
Before:
After:

fix(gmail): loading animation

---

styles/youtube/catppuccin.user.css

Fixes broken checkboxes in the settings menu of a video.
| --- | --- |
| ![Screenshot 2024-02-02 at 09 43 03 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/8e32a28d-a1f9-4b8d-8ee8-7627864de65e) | ![Screenshot 2024-02-02 at 09 43 34 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/97ca701a-8928-48f1-9ab6-45b9f0d655b2) |

fix(youtube): checkboxes

---

scripts/userstyles.yml
styles/twitter/assets/catwalk.webp
styles/twitter/assets/frappe.webp
styles/twitter/assets/latte.webp
styles/twitter/assets/macchiato.webp
styles/twitter/assets/mocha.webp
styles/twitter/catppuccin.user.css

Soothing pastel theme for Twitter.
template.

feat(twitter): init

---

scripts/userstyles.yml
styles/snapchat-web/assets/catwalk.webp
styles/snapchat-web/assets/frappe.webp
styles/snapchat-web/assets/latte.webp
styles/snapchat-web/assets/macchiato.webp
styles/snapchat-web/assets/mocha.webp
styles/snapchat-web/catppuccin.user.css

Theme for snapchat's web client.
can't really theme this section (or card) since theres no decent selector
the card is just transparent with a blur effect, background image is generated
template.

feat(snapchat-web): init

---

styles/chatgpt/catppuccin.user.css

Themes the login page (I got signed out and had to sign back in to ChatGPT and thought I'd theme the page lol).

feat(chatgpt): theme auth/login page

---

styles/bsky/catppuccin.user.css

Allows the bluesky theme to apply again after changes to the currently used theme selector
also fixes latte (i hope) by adding selectors for latte-specific things

fix(bsky): various parts

---

styles/gmail/catppuccin.user.css

Themes the Gmail logo while loading, themes the left sidebar better, removes theming of labels, themes icons in context menus / drop downs.

fix(gmail): various unthemed elements

---

styles/github/catppuccin.user.css

In #496, additional styling to tooltips was added but one selector wasn't specific enough and in some cases causes the wrong color to be used in the wrong place. This fixes that while also ensuring tooltips are still themed correctly :)

fix(github): tooltip colors accidentally affecting other elements

---

styles/github/catppuccin.user.css

Adds syntax highlighting to the web editor. It uses CodeMirror but our own port of that doesn't use the same variables so I sorta winged it based on the existing PrettyLights syntax highlighting.

feat(github): syntax highlighting in codemirror web editor

---

styles/github/catppuccin.user.css

Improves the selectors used to match GitHub's, I believe this closes #301 too.

fix(github): improve selectors

---

styles/chatgpt/catppuccin.user.css

The ChatGPT interface was updated today and these changes fix the issues that arose because of that (mostly just meant we can remove some extra classes and use variables more). I've spent a little time testing out various parts and it looks all set to me.

fix(chatgpt): update theme to match website updates

---

styles/github/catppuccin.user.css

Themes upvotes and downvotes in discussions (L366-L367), the progress bar at the top of the screen when loading (L426-L428), more tooltips (L433).

fix(github): various unthemed elements

---

scripts/userstyles.yml
styles/perplexity/README.md
styles/perplexity/catppuccin.user.css

Fixes:
- tooltip on the generate images/search images/search video on the right
- "Related" section borders at the bottom
- Codeblocks
- Primitive syntax highlighting
- Plus icons
- Settings menu indicators
- Many hover states
I'll maintain this, though I don't expect this to break often.

fix(perplexity): hover states, codeblock, syntax highlighting, seperators, icons

---

styles/youtube/catppuccin.user.css

Changing 'HDR' video quality badge to correct Catppuccin red.

fix(youtube): Changing 'HDR' video quality badge to correct Catppuccin red

---

styles/youtube/catppuccin.user.css

Fixes some icons to be `@text` instead of `@overlay0` since it implies a state difference which is not there (I checked how the same icons appeared without the theme to be sure). I also themed the search bar placeholder text.

fix(youtube): icon colors, search input placeholder

---

styles/youtube/catppuccin.user.css

previous PR I made fixed the description color when the desc is expanded, this fixes it when it's not.

fix(youtube): description color (when not exapnded)

---

README.md

Once this is merged we should update the release page by adding the following steps instead of the link to the main README:
```md
This is a rolling release that holds builds generated by the GitHub Actions build process. 
1. Download the `import.json` file from the "Assets" section below.
> [!TIP]
> If you want more control over what is included in the `import.json` file, e.g. all userstyles with the accent color `mauve`, see "[All Userstyles Import Generator](https://aui.ctp.uncenter.dev/)" by @uncenter.
3. Open the Stylus "manage" page.
4. Locate backup (on the left bar) and select import.
- Select the downloaded file.
5. Enjoy!
```
<details>
<summary>Preview</summary>
</details>

docs(README.md): move all userstyles instructions to release page

---

styles/migadu-webmail/catppuccin.user.css

Themes some parts of the compose modal that I missed earlier (borders, minimize/close icons) and updates the button styling to more accurately reflect default/success/warning/danger states.

fix(migadu-webmail): compose message modal, buttons

---

scripts/userstyles.yml

the previous commit fixed the shadow problem with latte on dark mode, this note is no longer needed

docs(twitch): remove no longer needed note

---

styles/twitch/catppuccin.user.css

button text color; closes #575

fix(twitch): button text color

---

styles/migadu-webmail/catppuccin.user.css

Fixes the color of icons/text inside success/danger/warning buttons not being overriden by disabled button styling.
|---|---|
| ![Screenshot 2024-02-28 at 22 10 53 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/9e0ae4a7-6e0a-41ea-8846-7d45022e7f53) | ![Screenshot 2024-02-28 at 22 11 31 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/761157dd-dfd7-448e-91bf-39eb5778137d) |

fix(migadu-webmail): disabled button color

---

styles/minesweeper/catppuccin.user.css

fix(minesweeper): accent-color

---

styles/github/catppuccin.user.css

Fixes the selectors to work properly with "Sync with system" (closes #584) and updates the auto-detection for unsupported themes. Also, fixes the header when logged out (closes #285, closes #284).

fix(github): selectors,  header when logged out

---

styles/chatgpt/catppuccin.user.css

Updates CSS override variables to match ChatGPT updates, fixes a border in dark mode, and themes the inline style of katex errors.

fix(chatgpt): match website updates, arbitrary unthemed elements

---

styles/npm/catppuccin.user.css

Noticed some more unthemed legacy syntax highlighting.

fix(npm): more legacy syntax highlighting

---

styles/wikipedia/catppuccin.user.css

update ver not needed beacuse the change is just removing already applied css
- [] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

fix(wikipedia): correct some small errors

---

styles/migadu-webmail/catppuccin.user.css

Fixes the icon colors of some buttons.

fix(migadu-webmail): icon colors

---

styles/npm/catppuccin.user.css

Sorry for the small change PRs. I realized I was darkening base instead of using a darker Catppuccin color for some reason... this fixes that.

fix(npm): use mantle for `<code>` element backgrounds

---

.github/workflows/pull-requests.yml

Disables it from running on PRs with a title containing `(tree-wide)` since those often edit so many files that the labeler workflow fails due to too many labels.
Side note: looks like we are pinned at a very specific version for the `actions/labeler` workflow - any reason for this? Can we / should we upgrade to https://github.com/actions/labeler/releases/tag/v5.0.0?

ci(pr-labeler): disable on tree-wide PRs

---

styles/nixos-search/catppuccin.user.css

Closes #619
[NixOS Search](https://search.nixos.org) has recently updated its frontend. This PR uses the new CSS variables to theme most of the website and using overrides for the remaining components.

fix(nixos-search)!: update style to work with new UI

---

styles/wikipedia/catppuccin.user.css

fix(wikipedia): black text -> white text in sidebar

---

styles/chatgpt/catppuccin.user.css

Adds an override for a primary background class due to specificity issues.

fix(chatgpt): primary background override

---

styles/youtube/catppuccin.user.css

enable yt logo by default
related to https://github.com/catppuccin/userstyles/issues/632

chore(youtube): enable youtube logo by default

---

styles/wikipedia/catppuccin.user.css

the quote text and infobox, closes #616

fix(wikipedia): assorted fixes

---

.stylelintrc.js

This rule is not needed since we outright disallow all `font-*` properties (and this just clogs up the maximum of 10 annotations that ca display on a PR).

chore(stylelint): disable font-family-no-missing-generic-family-keyword

---

styles/wikipedia/catppuccin.user.css

fix(wikipedia): color redirect thingy into green

---

styles/instagram/catppuccin.user.css

dm bubble color
| --- | --- |
| ![](https://github.com/catppuccin/userstyles/assets/29279972/2d0adc78-800c-4395-b162-dec80fc65b98) | ![](https://github.com/catppuccin/userstyles/assets/29279972/8e704069-c62d-433a-8c83-a09a4b9fc933) |

fix(instagram): direct message bubble color

---

styles/google/catppuccin.user.css
styles/twitter/catppuccin.user.css

fixes the selected image highlight + changes the review star color to be ctp yellow + description of image, border color is blue because the original was blue as well as the safesearch dropdown

fix(google): selected image highlight

---

styles/duckduckgo/catppuccin.user.css

definitions infobox coloring
| Before|After|
|---|---|
| ![image](https://github.com/catppuccin/userstyles/assets/29279972/34af53ea-f427-418b-aa5d-15bc8d8d2992) | ![image](https://github.com/catppuccin/userstyles/assets/29279972/1f6949e3-82d3-440b-bde8-69ef54978ca4)|

fix(duckduckgo): defenitions infobox coloring

---

styles/tabnews/catppuccin.user.css

This fixes seen posts and new post having similar color. Now it's a darker color.
Preview:

fix(tabnews): Contrast between seen posts and new posts

---

styles/youtube/catppuccin.user.css

transparent header bar not being themed. but it makes it non-transparent
before
after
Closes #677

fix(youtube): transparent header bar not being themed, but made header bar non-transparent

---

styles/github/catppuccin.user.css

Closes #662. I don't use latte much but I think some other parts could use lighter colors. I'm going to leave this PR in limbo for a bit to mess around with it.

fix(github): code block backgrounds

---

styles/formative/catppuccin.user.css

Fixes mathlive keyboard and other question elements like drag-and-drop choices, themes practice set UI

fix(formative): unthemed elements

---

styles/wikipedia/catppuccin.user.css

Updates syntax highlighting to use the generated variables from our official Pygments addon to the Python port.

refactor(wikipedia): use syntax highlighting from python pygments port

---

styles/duckduckgo/catppuccin.user.css

the translation infobox
<table>
<tr>
<td>
before
<td>
after
<tr>
<td>
<td>
</table>

fix(duckduckgo): translations infobox

---

styles/chatgpt/catppuccin.user.css

Moves the variables to the very bottom (as the template does now) to remove duplication in two different `@-moz-document`s, and cleans up a few comments and such.

refactor(chatgpt): move `@catppuccin` colors variable, cleanup

---

scripts/userstyles.yml

`nextjs` is not an icon, it should have been `nextdotjs`.

chore(nextjs): fix icon field

---

.github/workflows/website.yml

What I tried to do earlier is currently impossible, GitHub have it on their public roadmap for this functionality: https://github.com/github/roadmap/issues/636 
Frankly, I can't be bothered and it doesn't make sense to over-engineer the CI if I have to duplicate the secrets anyways, just copied the file from catppuccin/catppuccin

ci(website): dont bother with reusing workflow

---

styles/twitch/catppuccin.user.css

Themes predictions, disabled inputs and input placeholder text, the pause/play button when you tap space bar, and the text overlay on ads.

feat(twitch): predictions, inputs, pause/play button, ad text overlay

---

styles/github/catppuccin.user.css

Replaces GitHub's mona loading gif with a spinny Catppuccin logo gif, themes some additional vars that fixes controls (radio buttons) and various other elements.

feat: catppuccin loading gif, additional vars

---

styles/github/catppuccin.user.css

fix(github): use accent on radio buttons

---

scripts/userstyles.yml
styles/openmediavault/catppuccin.user.css

Changes the spelling from "OpenMediaVault" to "openmediavault", which is how they spell it on their website/branding (https://www.openmediavault.org/).

chore(openmediavault): use correct brand name spelling

---

styles/codeberg/catppuccin.user.css

Lets use the much much more robust ctp/gitea pages deployment urls instead of my forgejo instance

chore(codeberg): use the ctp/gitea pages deployment urls

---

scripts/deps.ts
scripts/lint/metadata.ts

This fixes an issue where, on Windows, paths would be prefixed with a leading `/`. This is invalid and would cause path resolution to fail. 
This does bump the minimum deno version 1.40. This requirement will need further discussion.

ci: fix path bugs on windows

---

README.md
scripts/userstyles.yml

This should mean we also don't have to include the extra steps on mastodon and etc.

docs: instance based websites

---

styles/instagram/catppuccin.user.css

Themes the ring around a user's profile picture in the story bar up top.

feat(instagram): theme story ring around profile picture

---

styles/chatgpt/catppuccin.user.css

For some reason OpenAI has two nearly identical login/auth pages, but on different domains with different tech stacks. Anyways, this themes the newer one and updates the old one.

fix(chatgpt): some other login page

---

styles/github/catppuccin.user.css

Themes danger buttons properly, fixes a bug with unread notifications on latte.

fix(github): danger buttons, notifications bug

---

styles/duckduckgo/catppuccin.user.css

on/off buttons + save and exit buttons on settings page + selected theme checkmark, closes #735

fix(duckduckgo): various unthemed elements

---

styles/github/catppuccin.user.css

Fixes the `--overlay-bgColor` variable being a shade wrong, themes the text selection color (in certain places).
| --- | --- |
| ![Screenshot 2024-04-02 at 17 30 29 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/15b0f5a6-5418-47ab-a195-0b0baedb7ea6) | ![Screenshot 2024-04-02 at 17 30 13 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/ed7d8a41-e345-4d83-a528-3aad6dfd6b9c) |

fix(github): overlay background color, text selection

---

styles/youtube/catppuccin.user.css

Fixes a change I made in #745 that broke icons in dark themes and themes another label in a popup menu.

fix(youtube): misc

---

styles/wikipedia/catppuccin.user.css

- Theme fundraising elements;
- Theme math equations.
Before:
After:

fix(wikipedia): Style fundraising elements & math equations

---

styles/duckduckgo/catppuccin.user.css

title.
<table>
<tr>
<td>
Before
<td>
After
<tr>
<td>
<td>
</table>

fix(duckduckgo): lyrics box text

---

styles/chatgpt/catppuccin.user.css
styles/pypi/catppuccin.user.css
styles/wikipedia/catppuccin.user.css

the `--ctp-base` variable used `@crust` instead of `@base`

fix(tree-wide): use base for --ctp-base variables

---

styles/vercel/catppuccin.user.css

Fixes unthemed elements, updates some vars (link color, secondary bg color).

fix(vercel): theme some regressions, use accent for link color

---

styles/youtube/catppuccin.user.css

Fixes a border in the video player's setting menu, removes `text-shadow` (blurry/fuzzy text) from the timestamp tooltip when hovering over the progress bar.

fix(youtube): misc player changes

---

styles/github/catppuccin.user.css

Themes mermaid diagrams (e.g. https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md#pull-request-review-process) and selected text.
| --- | --- |
| ![mermaid-unthemed](https://github.com/catppuccin/userstyles/assets/47499684/35dec686-fa88-4642-ae11-ce12a87e0791) | ![mermaid-latte-mauve](https://github.com/catppuccin/userstyles/assets/47499684/6a512da5-8dbf-4de4-af70-0e0643849eec) ![mermaid-macchiato-sapphire](https://github.com/catppuccin/userstyles/assets/47499684/24bfa3b8-46b4-47ba-b069-4b05534911a9) |

feat(github): theme mermaid diagrams and ::selection

---

.stylelintrc.js

https://github.com/catppuccin/userstyles/pull/760#discussion_r1551103677. I've confirmed that this fixes the lint message.

chore(lint): disable keyframes-name-pattern

---

styles/github/catppuccin.user.css

Themes various parts around GitHub Actions, including ansi text within Actions logs.

fix(github): misc + actions ansi text

---

styles/github/catppuccin.user.css

Various fixes to disabled buttons to make them properly have contrast while sticking with Catppuccin theme.

fix(github): improvements to disabled buttons

---

styles/instagram/catppuccin.user.css

title
<table>
<tr>
<td>
Before
<td>
After
<tr>
<td>
<td>
</table>

fix(instagram): direct messages not respecting chosen flavor

---

README.md

I don't think you can do relative markdown links with anchors in other files, happy to change it if you can.
I've followed the link format widely seen in [GitHub's documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository#troubleshooting-cloning-errors).

docs(README): link to `userstylesyml.md` for maintainer requests

---

styles/youtube/catppuccin.user.css

Example of ambient mode flowing into header.

fix(youtube): ambient mode header improvments

---

styles/github/catppuccin.user.css

Themes one very specific button (the "suggest changes" button in the toolbar of PR comment box on some occasions), changes the outline color of input elements from blue to accent.

fix(github): "invisible" button bg color, focus outline

---

styles/youtube/catppuccin.user.css

Fixes the text on top of the reels video player being `@text` all the time instead of `@white`. Also themes the notification bell button properly.

fix(youtube): text on top of reels video player

---

deno.json
deno.lock
scripts/types/userstyles.d.ts

Fixes the generate workflow, might be worth looking into if we can make it not fail on purely additive properties but unsure if that's possible and/or a slippery slope to worse behaviour.

chore(deps): update `catppuccin/catppuccin` schema

---

styles/github/catppuccin.user.css

Fixes the header (on the Gists website at least) and an unthemed hamburger menu on the main website's logged out header.

fix(github): header shenanigans

---

scripts/userstyles.yml

This avoids a headache I ran into while implementing https://github.com/catppuccin/website/issues/61 as the URL in [catppuccin/catppuccin](https://github.com/catppuccin/catppuccin/blob/89111dff968c42f9774c18c2957465616b51b205/resources/ports.yml#L256) is `Tnixc`.
We may want to enforce our own rules such as lowercase URLs to avoid this type of mismatch between repositories in the future.
Also this does raise consistency concerns which should be discussed further in another issue, e.g. the `name` field could potentially be different too.

chore(maintainers): update url for `Tnixc`

---

styles/youtube/catppuccin.user.css

Themes the subscribe button on youtube shorts.

fix(youtube): additional button variant

---

styles/snapchat-web/catppuccin.user.css

Fixes the story reply text background.
Without theme:
Old version of theme:
New version of theme:

fix(snapchat-web): Story reply text.

---

styles/bsky/catppuccin.user.css
styles/chatgpt/catppuccin.user.css
styles/formative/catppuccin.user.css
styles/hackage/catppuccin.user.css
styles/hacker-news/catppuccin.user.css
styles/minesweeper/catppuccin.user.css
styles/npm/catppuccin.user.css
styles/perplexity/catppuccin.user.css
styles/planet-minecraft/catppuccin.user.css
styles/spotify-web/catppuccin.user.css
styles/twitch/catppuccin.user.css
styles/twitter/catppuccin.user.css
styles/wikipedia/catppuccin.user.css
styles/youtube/catppuccin.user.css

This removes extra `&<space>` syntax. `&` followed by a space is the same thing as if it weren't there (useless).

refactor(tree-wide): cleanup extra syntax

---

styles/youtube/catppuccin.user.css

This PR adds Theming to the skeleton when loading the youtube homepage.
Note: Top is new opened in chromium and bottom is old opened in firefox

fix(youtube): theming for skeleton

---

styles/twitter/catppuccin.user.css

| --- | --- |
| ![Screenshot 2024-04-11 at 16 18 29 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/dd892de3-74eb-45fd-ac5c-f164cd4e9bd4) | ![Screenshot 2024-04-11 at 16 17 57 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/5cbc8142-60bf-413e-8cf3-2da43b37fc87) |
Wasn't sure where to put it, just stuck at at the end. Lmk if I should move it somewhere else!

fix(twitter): translated by google svg

---

styles/youtube/catppuccin.user.css

Themes description text, icons, and popup menus on channel pages.

fix(youtube): custom wiz elements on channel page

---

styles/github/catppuccin.user.css

- Currently there are two Catppuccin colour palettes in GitHub's userstyles; one at the top of the code, and one at the bottom.
- This caused changing the colour palette on the top to not have an effect on the resulting style.
- This change removes the one on the top, leaving only one colour palette.

fix(github): remove duplicate colour palette

---

styles/youtube/catppuccin.user.css

Fixes low contrast for the YouTube progress bar on thumbnails
Before: 
After:

fix(youtube): low contrast for the progress bar on thumbails

---

styles/pypi/catppuccin.user.css

fix(pypi): unstyled text

---

styles/wikipedia/catppuccin.user.css

This puts the green redirect highlight behind an option, as it does not seem to be Wikipedia's default behavior and feels opinionated.
I've done this instead of outright requesting to remove it, as the [contributing guide](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md) does not seem to outright prevent this since it's just a color change. However, it feels against the spirit of the opinionated section to me, and I also just don't like the green 🙃
On (previously the only behavior):
Off (added in this PR):

feat(wikipedia): add option for redirect highlight

---

styles/youtube/catppuccin.user.css

Low contrast for the YouTube video player's progress bar
Before, the background was unstyled and could be hard to see at times on Mocha.
After, the background now uses a translucent Surface 0, and the buffer indicator uses an opaque Overlay 0, making it easier to see:
The white background makes the buffer indicator slightly harder to see, but I do not think this is an issue as the YouTube default also has bad contrast:
Latte's contrast suffers from this, so the progress bar is untouched there.

fix(youtube): low contrast for video player progress

---

styles/whatsapp-web/catppuccin.user.css

Whatsapp added a nav bar to the left side. It had the wrong background color so I fixed it.
|-|-|
|![image](https://github.com/catppuccin/userstyles/assets/27358071/f892b4f5-15ac-4632-bc62-c5602f7bafb5)|![image](https://github.com/catppuccin/userstyles/assets/27358071/a5adeec3-7647-47ac-a568-48b1ce086668)|
Closes #816.

fix(whatsapp-web): nav bar background

---

styles/chatreplay/catppuccin.user.css

fix(chatreplay): respect chat colors

---

styles/youtube/catppuccin.user.css

Themes buttons on top of the shorts video player, and adjusts some buttons to improve how they appear against the background.

fix(youtube): buttons and shorts related

---

styles/wikipedia/catppuccin.user.css

this fixes theming issues at [ja.wikipedia.org](https://ja.wikipedia.org/wiki/%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8)

fix(wikipedia): theming broken at ja.wikipedia.org home page

---

styles/youtube/catppuccin.user.css

| - | - |
| ![Screenshot 2024-04-26 at 16 21 19 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/fa7b9cb0-b9be-4827-97aa-4757169151c0) | ![Screenshot 2024-04-26 at 16 20 49 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/5a8b56c5-8dc6-4700-a778-ad8a0be2f9c6) |

fix(youtube): shorts comments popup backdrop

---

styles/trinket/catppuccin.user.css

fix(trinket): Style "beta" text

---

styles/chatgpt/catppuccin.user.css

Fixes some new issues on the two login pages of ChatGPT and themes a border around the OpenAI logo that seems to have changed (or maybe just my eyesight has improved and I didn't notice it earlier, who knows).

fix(chatgpt): misc login page and border theming

---

styles/nixos.wiki/catppuccin.user.css

Switches to using our Python Pygments port for theming syntax highlighting (it is mediawiki as well, like Wikipedia). Upon thinking about it we don't have this stuff mentioned anywhere in the docs... 👀

refactor(nixos.wiki): use pygments for syntax highlighting

---

styles/gmail/catppuccin.user.css

uh good question, off the top of my head, i can think of a few:
- removes styling for emails
- dropdown menu icons in email
- the x new as well as it's subtext
- some assorted icons
- the unsub button on a newsletter
- label drop down
- closes #553 as well
- no i do not plan on maintaining this userstyle, i only fixed it up because it was annoying me lol and i hope you're happy uncenter

fix(gmail): assorted changes

---

styles/whatsapp-web/catppuccin.user.css

Whatsapp added a filter bar. It had the wrong colors so I fixed it.
Also closes #837.
|-|-|
| ![Screenshot 2024-05-06 194836](https://github.com/catppuccin/userstyles/assets/27358071/f4546164-5dcf-4f96-af8b-3a4dcf4addf5) | ![Screenshot 2024-05-06 194746](https://github.com/catppuccin/userstyles/assets/27358071/05db651c-6801-4a2d-8a7d-195a6b286c02) |

fix(whatsapp-web): filters fix

---

styles/migadu-webmail/catppuccin.user.css

Messages are much easier to read with these default styles.

fix(migadu-webmail): untheme message content

---

styles/google/catppuccin.user.css

Fixes un-themed account (`iframe`) menu.
|Before|After|
|--------|--------|
|![image](https://github.com/catppuccin/userstyles/assets/29287159/be977994-06b2-4ac1-ac15-2f7071bb54e6)|![image](https://github.com/catppuccin/userstyles/assets/29287159/e7240d72-7d74-4b0c-b30e-6b23c8684097)|

fix: account iframe themed correctly

---

styles/chatgpt/catppuccin.user.css

fix(chatgpt): swap two vars, theme toggle and "which response do you prefer"

---

styles/github/catppuccin.user.css

| - | - |
| ![image](https://github.com/catppuccin/userstyles/assets/47499684/7d2b4e72-ec08-454a-8dfc-1c17b21dd9d7) | ![image](https://github.com/catppuccin/userstyles/assets/47499684/5ddb08e6-2640-4be2-b39b-bd05cdf942ee) | 
Also there is another change in here for a random button border.

feat(github): theme activity overview graph

---

styles/migadu-webmail/catppuccin.user.css

Previous selector wasn't working 100% of the time for some reason.

fix(migadu-webmail): adjust message content selector

---

styles/duckduckgo/catppuccin.user.css

- Fixed Text overflow fade in scrollable toolbox
- Themed Duckduckgo open in application button in header of the page
- Themed Mobile footer and footer separator 
- Tweaked settings panel's colors
- Themed Mobile More results button
- Edited On/Off switches for clarity
note: still needs some aditional finishing touches, but this should be the majority of the fixes I could find

fix(duckduckgo): misc

---

docs/tips-and-tricks.md

Adds `&nbsp;` after some paragraphs like the rest, removes unneeded HTML markup.

docs(tips-and-tricks): add nbsp and cleanup

---

styles/codeberg/catppuccin.user.css

| - | - |
| ![Screenshot 2024-05-16 at 10 16 54 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/75d85b18-8a3b-460a-af01-4c4b15672b5d) | ![Screenshot 2024-05-16 at 10 16 43 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/928522fa-5556-4565-80fe-7563c341a7b2) |

fix(codeberg): active tab text color

---

styles/github/catppuccin.user.css

Teeny fix for a background color used in like one place.

fix(github): fade --bgColor-neutral-muted

---

styles/youtube/catppuccin.user.css

Themes premiere badges on thumbnails and both live and premier on channel pages.

fix(youtube): theme some live & premiere badges

---

styles/twitter/catppuccin.user.css

I missed some of the URLs by mistake
This should add the remaining X URLs that I forgot to add in my last PR, I made sure api.x.com was in use via inspect element. However, the CDN still references Twitter somewhat so it is still unchanged from twimg.com however might change in the future

fix(twitter): Add missing x.com URLs

---

styles/github/catppuccin.user.css

Themes some status border colors (e.g. delete repo input border).

fix(github): misc vars

---

styles/duckduckgo/catppuccin.user.css

<table>
<tr>
<td>
before
<td>
after
<tr>
<td>
<td>
</table>

fix(ddg): more news in carousel button background

---

styles/chatgpt/catppuccin.user.css

fix(chatgpt): inline style override

---

styles/crates.io/catppuccin.user.css

Themes the following yanked badge:
Can be seen on crate pages like https://crates.io/crates/url_validator/0.1.3.

fix(crates.io): yanked badges

---

styles/docs.rs/catppuccin.user.css

fix(docs.rs): misc

---

scripts/userstyles.yml
styles/mdbook/catppuccin.user.css
styles/mdbook/preview.webp

Themes websites using mdBook. Currently added the domain for the Rust books: https://doc.rust-lang.org/cargo/index.html, https://doc.rust-lang.org/book/title-page.html.
template.

feat(mdbook): init

---

styles/docs.rs/catppuccin.user.css

Themes these kind of links in the source code:

fix(docs.rs): background of links in source viewer

---

styles/docs.rs/catppuccin.user.css

Apply the docs.rs userstyle to https://doc.rust-lang.org (aka docs.rs/std)

feat(docs.rs): apply to doc.rust-lang.org

---

styles/mdbook/catppuccin.user.css

Apply the mdbook userstyle to https://rust-book.cs.brown.edu

feat(mdbook): apply to rust-book.cs.brown.edu

---

styles/proton/catppuccin.user.css

Fixes #828 by setting `color-scheme: light;` for the iframe containing the message.

fix(proton): light color scheme for message iframe

---

styles/hackage/catppuccin.user.css

* Fixed the quick jump and dropdown (Instances) menus in Haddock documentations.
* Colored the MathJax settings and applied invert to the image-rendered math for dark themes.
* Colored the text of submit buttons in the advanced search page.

fix(hackage): color haddock menus

---

styles/hyperpipe/catppuccin.user.css

* Colored the button gradient on albums and playlist.

fix(hyperpipe): color the play button

---

styles/mastodon/catppuccin.user.css

fix(mastodon): active icon button color

---

styles/mastodon/catppuccin.user.css

realized that confirmation was not styled + fixes a regression caused by my last PR
<table>
<tr>
<td>
before
<td>
after
<tr>
<td>
<td>
</table>

fix(mastodon): active icon button color + confirmation prompt

---

styles/wikipedia/catppuccin.user.css

The `<tbody>` child of the tracklist table (`.tracklist`) now inherits the parent text color. 
The last row (`.tracklist-total-length`) is in inverted colors (it was already inverted, I've just changed the background to `@overlay1`.)
Closes #792.
Here's some screenshots of the [Future, Present Past](https://en.wikipedia.org/wiki/Future_Present_Past) track listing using mauve accents.
- Latte:
- Frappe:
- Macchiato:
- Mocha

fix(wikipedia): Legibility of text color in tracklist tables

---

styles/elk/catppuccin.user.css

Fixes that button being a different color than the background.

fix(elk): disable saturation filter

---

.github/CODEOWNERS
scripts/generate/main.ts

This commit ensures that explicit approval
from catppuccin/userstyles-staff is required
for paths that are responsible for managing
the repository.

build(CODEOWNERS): protect sensitive paths

---

docs/tips-and-tricks.md

See changes. Uses the correct list of variables, adds instruction for adding `#rgbify`.

docs(tips-and-tricks): update syntax highlighting tip

---

styles/wikipedia/catppuccin.user.css

Fixes issues with background-color on the `<div class="noarticletext">` tag and tags with `id=\#sisterproject` in some languages.
Closes #670.
Some screenshots are included in my comment on that issue.

fix(wikipedia): .noarticletext div background-color

---

styles/stack-overflow/catppuccin.user.css

fix(stack-overflow): notification toasts

---

template/catppuccin.user.css

In the template, "theming" is spelled like "themeing" (with an extra e). this change fixes that

fix(template): typo

---

deno.json
deno.lock

Renovate is having some trouble parsing this as it's looking for it in the npm registry. Changing it to the `npm:` specifier should hopefully fix this.
When the deno-lib is brought into userstyles, we can look towards reverting this change to put more dependencies into the cache.

build: use `npm:` instead of `esm.sh`

---

deno.json
deno.lock
scripts/lint/stylelint-custom/optimizedSvgs.js
scripts/lint/stylelint.ts
scripts/types/mod.ts
scripts/update-types.ts
styles/ichi.moe/catppuccin.user.css

Converts any and all direct `npm:` imports to plain imports and stores the alias in the deno.json for clarity. I then regenerated the lockfile, and ran all scripts to make sure all dependencies were added.

build: regenerate deno lockfile

---

.github/CODEOWNERS
scripts/generate/main.ts

This ensures that edits to any dependencies / workflows / etc need to be approved by userstyles staff.

chore(CODEOWNERS): make staff own `.github/`

---

styles/duckduckgo/catppuccin.user.css

this includes the always private icons + text, and their new ai chat models among other things

fix(duckduckgo): assorted elements

---

styles/instagram/catppuccin.user.css

themes the new notes feature instagram added as well as fix the direct messages not being themed properly

fix(instagram): direct message fixes

---

styles/wikipedia/catppuccin.user.css

This gives the correct coloring for selflinks on Wikipedia.
Before, when on the Wikipedia page for Family BASIC:
After:
This matches default Wikipedia:

fix(wikipedia): selflink anchors

---

styles/wikipedia/catppuccin.user.css

fix(wikipedia): broken background on some external links

---

styles/youtube/catppuccin.user.css

Makes buttons like the two here look better by adding a different background on hover and matching the hover background of the outline button more closely to YouTube's own styling:

fix(youtube): improve button styling

---

scripts/userstyles.yml

User has deleted their GitHub account.
Initially, I thought about keeping the name
but linking to @ghost for the URL but that
feels a bit odd.
Going forward, we should just remove accounts
that have been deleted and are rendered on GitHub
as @ghost.

chore(maintainers): remove `haiksgithub`

---

styles/lemmy/catppuccin.user.css

Latte theme with pink (or similarly light) accent choices resulted in illegible body text, such as comments.
This fixes the issue by setting body text to `@text` color instead of @accent-color.
**(before) Latte Pink with `@accent-colored` text as prior:**
**(after) Resolved with `@text` colored text:**
**NB:** `@accent-color` is still used across the theme elsewhere.

fix(lemmy): use `@text` for body text

---

styles/twitch/catppuccin.user.css

Some weird hard coded and overriden accents are now double overridden by this PR :)

fix(twitch): misc accent-related

---

styles/go.dev/catppuccin.user.css

Sometimes the `data-theme` attribute doesn't exist, like if it is your first time visiting the website. This adjusts the theme application selectors to use `prefers-color-scheme` if there is no attribute set, as if `data-theme="auto"`.

fix(go.dev): adjust dark/light application selectors

---

scripts/userstyles.yml

i don't use arch anymore and i don't see myself maintaining this style so yeah

chore(arch-wiki): move @GenShibe to `past-maintainers`

---

styles/google-gemini/catppuccin.user.css

Gemini updated and header color broke, this pr fixes it.
and also other fixes.
- Header
- Mini fab hover/focus
- Action tooltip
- Tunable menu
- Recitation button
- Buttons focus text color
- Outline button
- Divider color
- Dialog container

fix(google-gemini): misc

---

styles/pinterest/catppuccin.user.css

Fixes readability in dark mode themes, as well as other fixes:
- Search bar color
- Top bar color matches base
- Change save button from red to accent color
- "More ideas" and "Organize" hover states
- Hide background of "created" and "saved" buttons on profile
- Remove bar behind "created" and "saved" buttons on profile
- "Account and more options" popup looks better in dark mode
- other miscellaneous fixes

fix(pinterest): misc

---

styles/porkbun/catppuccin.user.css

Fixes these green success buttons and organizes the CSS a bit.

fix(porkbun): success buttons

---

styles/stack-overflow/catppuccin.user.css

fix(stack-overflow): jobs page

---

styles/twitch/catppuccin.user.css

Themes mentions in chat, which through a roundabout set of vars ends up using this var.

fix(twitch): chat mention backgrounds

---

styles/chess.com/catppuccin.user.css

fix(chess.com): wrap variables in body selector

---

styles/advent-of-code/catppuccin.user.css

fix(advent-of-code): unthemed text and hover

---

styles/go.dev/catppuccin.user.css

Fixes miscolored info banners in `pkg.go.dev`

fix(go.dev): info banner

---

styles/codeberg/catppuccin.user.css

Items in secondary menu colors are reversed when they are hovered but not for active(selected) one.
Inline code blocks use accent colors and it makes them hard to read.
Here are screenshots(no secondary menu one because I couldn't figure out how to screenshot while hovering items)

fix(codeberg): secondary menu, inline code

---

styles/pypi/catppuccin.user.css

links were a solid colour because of a previous update on pypi's side

fix(pypi): remove link background

---

styles/invidious/catppuccin.user.css

Updates the border colors from crust to surface1/2, removes scrollbar changes which went beyond just color customization.

fix(invidious): update border colors and remove scrollbar changes

---

styles/youtube/catppuccin.user.css

Profile cards are not themed.
|before|after|
|-|-|
|![image](https://github.com/user-attachments/assets/c0c2ef3f-2e7d-42cd-9659-97c2e98d6ffa)|![image](https://github.com/user-attachments/assets/1913e248-38a6-40ba-8e93-997bfe9e1186)|
|![image](https://github.com/user-attachments/assets/99fc7db4-33ef-44f3-be17-7e84b6b14214)|![image](https://github.com/user-attachments/assets/96ee4ce0-c18b-4f71-bcd1-828b0001c89c)|

fix(youtube): profile card

---

styles/lichess/catppuccin.user.css

This adds the option for the pawn/rook/knight/bishop/queen/king pieces to not be styled, which allows the user to set a custom theme through lichess' UI

feat(lichess): add `stylePieces` option

---

styles/modrinth/catppuccin.user.css

fix(modrinth): unthemed logo

---

styles/wikiwand/catppuccin.user.css

fix(wikiwand): citation in infobox and lang selector

---

styles/pypi/catppuccin.user.css

fix(pypi): unthemed text

---

.github/PULL_REQUEST_TEMPLATE/userstyle-creation.md
docs/userstyle-creation.md

update the catwalk link in the docs and the pr template
> This tool has moved to a separate repository to reduce the increasing complexity of managing a monorepo. To find code, documentation, and releases starting with and after [v1.3.1](https://github.com/catppuccin/catwalk/releases/tag/v1.3.1), visit [catppuccin/catwalk](https://github.com/catppuccin/catwalk).
\- [catppuccin/toolbox](https://github.com/catppuccin/toolbox/tree/main/catwalk)

docs: update catwalk links

---

styles/modrinth/catppuccin.user.css

Fixes unthemed 2nth table rows
screenshots (from [Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat)):
before:
after:

fix(modrinth): theme 2nth table row 

---

styles/modrinth/catppuccin.user.css

themes `--color-ad-highlight` (links in highlighted ads), `--color-gray` (the line under markdown headers), `--color-accent-contrast` (markdown tables 2nth row)
also removed the "2nth table row" section since it got replaced by `--color-accent-contrast`

fix(modrinth): unthemed variables

---

styles/pronouns.page/catppuccin.user.css

fix(pronouns.page): social buttons

---

styles/cinny/catppuccin.user.css

fix(cinny): footer

---

styles/stack-overflow/catppuccin.user.css

Not entirely sure what `background-image: none` was originally for, but I checked all domains and can't find it. It was messing up some other areas. Also removed an extra classname.

fix(stack-overflow): avatar fix

---

styles/youtube/catppuccin.user.css

Closes #1137. Colors the YouTube and Shorts icons, and the video and loading progress bars in some clients.

fix(youtube): color icons and progress bars

---

styles/youtube/catppuccin.user.css

fix(youtube): unthemed knob

---

styles/tuta/catppuccin.user.css

fix(tuta): logo

---

styles/npm/catppuccin.user.css

sorry if my PRs are a bit bearable to review

fix(npm): misc syntax highlighting

---

scripts/lint/file-checker.ts
scripts/lint/logger.ts
scripts/lint/main.ts
scripts/lint/metadata.ts
scripts/lint/stylelint.ts
scripts/utils.ts

Was reviewing a PR (#1160) and found it odd that the metadata differences were reported as warnings rather than errors, as we should not be merging a PR in such a state. This PR refactors the logging implementation to make logging warnings vs errors clearer, and switches the metadata logging to be all errors instead of warnings.

fix(lint): use errors instead of warnings, refactor log impl

---

styles/go.dev/catppuccin.user.css

fix(go.dev): unthemed border

---

styles/youtube/catppuccin.user.css

if your wondering where this is, just go to any short's description and you should find this

fix(youtube): shorts stats values

---

styles/pronouns.page/catppuccin.user.css

fix(pronouns.page): search bar focus

---

styles/spotify-web/catppuccin.user.css

fix(spotify-web): unthemed border on playlist details

---

styles/perplexity/catppuccin.user.css

This fixes nearly everything on this userstyle because it now themes the tailwind utility classes. 
Note:
- please check the `ring` theming and see if it's ok. It looks fine to me as it's used very sparingly but it's not ideal.
Before:
After:

refactor(perplexity): rewrite

---

styles/porkbun/catppuccin.user.css

fixes the unthemed form control focus

fix(porkbun): form control focus

---

styles/google-photos/catppuccin.user.css

i was going to fix these on my previous PR on google photos but i forgot to
<details>
<summary>before/after</summary>
<hr>
<hr>
</details>

fix(google-photos): text and labels

---

styles/pronouns.page/catppuccin.user.css

fix(pronouns.page): disabled buttons

---

styles/wikiwand/catppuccin.user.css

fixes syntax highlighting aswell as some borders too
<details>
<summary>before/after</summary>
<hr>
</details>

fix(wikiwand): syntax highlighting

---

styles/libreddit/catppuccin.user.css

fixes unthemed thumbnail titles
also this is going to be my last pr before deleting the fork as i got way more stuff to do outside catppuccin
<details>
<summary>before/after</summary>
</details>

fix(libreddit): thumbnail title

---

styles/proton/catppuccin.user.css

- fix flashbang in login page
- add opposite version of `#lightenOrDarken` to fix contrast issues in latte
- add new missing vars

fix(proton): login page and latte fix

---

styles/brave-search/catppuccin.user.css

Fixes unthemed settings dropdown in the top right corner

fix(brave): settings popup 

---

styles/proton/catppuccin.user.css

- added color overrides for the new Proton Wallet logo in the app switcher
I might look into the details and enable this userstyle for Proton Pass and Wallet in the future, but there are some weird inline styles left in Proton Pass and I still haven't got access to Proton Wallet so yeah it's just maybe.

fix(proton): proton wallet logo

---

styles/stylus/catppuccin.user.css

Closes #813 
Fixes various unthemed elements in stylus:

fix(stylus): unthemed elements

---

styles/pinterest/catppuccin.user.css

fixed unthemed elements
save button & hovering on save button
hovering popups
more options menu
image search popup
the search bar (there was a white shadows on it)
the comment bar (it wasn't round and the background was all dark)
this section was sometimes unthemed
the "open external link popup" when you hover over a pin
pin body shadow
parts not loaded yet/the void/skeleton/<html> element

fix(pinterest): unthemed elements

---

styles/instagram/catppuccin.user.css

title.
| Before | after |
| ------------- | ------------- |
| <img width="320" alt="image" src="https://github.com/user-attachments/assets/79d86d36-8513-4772-816d-58523b7e8638">  | <img width="334" alt="image" src="https://github.com/user-attachments/assets/2273d1a5-3a0d-49b1-a0a4-4243542c3c16">  |

fix(instagram): links in direct messages having horrible contrast

---

styles/trinket/catppuccin.user.css

fixes the logo disappearing on the main/plans page

fix(trinket): logo disappearing

---

styles/wikiwand/catppuccin.user.css

This updates the userstyle for omni wikiwand. This is a breaking change for users still on the old wikiwand version, but as I understand it, they have migrated fully to omni wikiwand.
Notes:
- Tables are somewhat broken, but they are broken without this userstyle too, so ¯\\\_(ツ)_/¯
- Syntax highlighting in some places might have been updated, I couldn't check if that's broken
This closes #1171

refactor(wikiwand): rewrite for omni

---

styles/modrinth/catppuccin.user.css

fixes a unthemed dropdown icon at the mods page

fix(modrinth): dropdown icon

---

styles/porkbun/catppuccin.user.css

fixes the broken help button on porkbun
i also removed ``&:hover`` because that doesn't do anything anymore

fix(porkbun): help button

---

styles/perplexity/catppuccin.user.css

Search goals in pro-search mode are unthemed when they are hovered.
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/fb1cc542-b52d-4803-9f77-1e699bccbc1f)|![image](https://github.com/user-attachments/assets/295285f1-fe6d-406f-b0ae-17a5a7c59868)|

fix(perplexity): search goals in pro-search mode

---

styles/chess.com/generate.py

Messed up in #1224 with the paths, this fixes it, as well as adding a shebang so the file can be executed with uv run (and providing a little instruction for users of it in the future).

fix(chess.com): correctly resolve paths to assets, add uv run shebang

---

styles/github/catppuccin.user.css

Fixes tooltips - not sure if they changed the vars recently or something, I thought they had been themed previously and I only started to notice this week.

fix(github): tooltips

---

.vscode/settings.json
styles/chatreplay/catppuccin.user.css
styles/hacker-news/catppuccin.user.css
styles/vikunja/catppuccin.user.css
styles/wikipedia/catppuccin.user.css

add this default css to the styles missing it (which fixes the selection background color not being themed)
```less
color-scheme: if(@lookup = latte, light, dark);
::selection {
background-color: fade(@accent-color, 30%);
}
input,
textarea {
&::placeholder {
color: @subtext0 !important;
}
}
```
there are styles that doesn't have this but i didn't add it to them manually
- `codeberg`: imports css from the gitea theme (which already has selection background theming)
- `shinigami-eyes`: it's an extension and only requires changing colors related to the extension's elements and not the whole page

chore(tree-wide): add missing default css to 4 styles

---

styles/github/catppuccin.user.css

Just started noticing this change where certain buttons had the wrong color (like the upload media one when writing a comment is accent when it should be text), seems like a change this week. Updates this var to match GitHub's.

fix(github): invisible button fg color

---

styles/arch-wiki/catppuccin.user.css

Fixes several unthemed containers througout the website, as well as texts with unreadable colors.
Closes #896

fix(arch-wiki): containers displayed with wrong colors

---

styles/youtube/catppuccin.user.css

- changed `--yt-spec-raised-background` from `@base` to `@surface0` (because the search suggestions background should be a bit brighter than the main background)
- theme the video duration on the thumbnails
- make the description background darker (same color as the buttons like in unthemed youtube) by changing `--yt-spec-badge-chip-background` to `@surface0` on non-latte flavors
- make the enabled menu item switch background colored with the accent color

fix(youtube): misc elements and adjust background colors

---

.envrc
.gitignore

This adds an `.envrc` file to automatically use the nix flake dev shell when entering this repository (for direnv users)

chore: add .envrc for direnv

---

README.md

Closes #1254. Brings the instructions from https://github.com/catppuccin/userstyles/releases/tag/all-userstyles-export into the main README instead of requiring an extra step. Still working on organizing and displaying the two methods of installation.
Plan for updated release notes contents is:
```diff
This is a rolling release that holds builds generated by the GitHub Actions build process. 
+ See the [usage instructions](https://github.com/catppuccin/userstyles#usage) for more information.
- 
- ### Usage instructions
- 
- 1. Download the `import.json` file from the "Assets" section below.
- 
- > [!TIP]
- > If you want more control over what is included in the `import.json` file, e.g. all userstyles with the accent color `peach`, see "[All Userstyles Import …
```

docs(README.md): update usage instructions and section headings

---

styles/google-drive/catppuccin.user.css

The logo had become unthemed due to the autogenerated classes changing. This updates the selector and uses a more stable attribute (`src`).

fix(google-drive): update logo selector

---

styles/youtube/catppuccin.user.css

Fixes the video highlight being unthemed.
I'm also gonna start to make more simple and easy-to-review PRs rather than last time where these PRs were really bad. (and also stop reviewing init PRs)
<details>
<summary>Before & After</summary>
</details>

fix(youtube): video highlight

---

styles/gmail/catppuccin.user.css

Fixes the header icons (3 to the left of pfp, menu/hamburger on the far left), fixes the search bar input background, and themes a banner for adding recovery info.

fix(gmail): update header icons and search bar selectors, banner message

---

styles/cobalt/catppuccin.user.css

I rewrote cobalt so it can be compatible with the new UI.
Fixes #1284

refactor(cobalt): support for new ui

---

styles/gmail/catppuccin.user.css

They changed the classes literally hours after #1281 -_-, this updates them yet again. Also themes another class for tooltips.

fix(gmail): header icons and search bar, other tooltip variant

---

styles/cobalt/catppuccin.user.css

fix(cobalt): applicator selectors & unthemed vars

---

styles/cobalt/catppuccin.user.css

Just noticed this as well, the hover over a button/tab on the sidebar was unthemed.

fix(cobalt): sidebar hover & donation page

---

styles/hacker-news/catppuccin.user.css

Themes some text on the login page which is just the page default, setting it here works and presumably fixes other text like it.

fix(hacker-news): set body text color

---

styles/github/catppuccin.user.css

fixes unthemed data graphs on the enhanced repo insight views
<details>
<summary>before & after</summary>
</details>

fix(github): updated enhanced repo insights views

---

styles/hacker-news/catppuccin.user.css

use the accent color instead of a mix of peach and yellow allegedly called "orange" (never heard of it)
it wasn't being applied correctly so i added `:root`
there isn't any reason links in comment should be colored differently. also hovered links now are colored with sky (as per the style guide)

fix(hacker-news): use accent for brand, link & selection colors

---

styles/paste.rs/catppuccin.user.css

Fix syntax highlighting since last update

fix(paste.rs): syntax highlighting token selectors, code background

---

styles/stylus/catppuccin.user.css

fix(stylus): delete button

---

styles/mastodon/catppuccin.user.css

Fixes the system theme not working on https://mastodon.social  by adding ``.theme-system`` to the applicator selectors

fix(mastodon): add `.theme-system` to applicator selectors

---

styles/vikunja/catppuccin.user.css

Fixes icon buttons having icon with different color than text and the unthemed loading spinner.

fix(vikunja): fix icon buttons & loading spinners

---

styles/advent-of-code/catppuccin.user.css
styles/crowdin/catppuccin.user.css
styles/invokeai/catppuccin.user.css
styles/lastfm/catppuccin.user.css
styles/openmediavault/catppuccin.user.css
styles/paste.rs/catppuccin.user.css
styles/pinterest/catppuccin.user.css
styles/quizlet/catppuccin.user.css
styles/spotify-web/catppuccin.user.css

userstyles that depend on the user's system theme use this snippet from the template style:
```less
@media (prefers-color-scheme: light) {
:root {
#catppuccin(@lightFlavor, @accentColor);
}
}
@media (prefers-color-scheme: dark) {
:root {
#catppuccin(@darkFlavor, @accentColor);
}
}
```
however some userstyles doesn't have the `:root` part which results in the selection background color not working

refactor(tree-wide): add missing `:root` to 9 styles

---

styles/youtube/catppuccin.user.css

(see bottom of image)
| --- | --- |
| ![CleanShot 2024-09-14 at 14 57 48](https://github.com/user-attachments/assets/b99c5093-8086-4771-a847-8127cde1ef0b) | ![CleanShot 2024-09-14 at 14 57 28](https://github.com/user-attachments/assets/d787d4c2-71f2-471b-80d9-fd42e148b43f) |

fix(youtube): shorts text on homepage

---

styles/mastodon/catppuccin.user.css

Fixes a bunch of unthemed stuff I found on the about page (https://mastodon.social/about) including unthemed text

fix(mastodon): about page

---

styles/youtube/catppuccin.user.css

Reverts a variable change that unintentionally messed up other places.

fix(youtube): revert `--yt-spec-raised-background` back to base

---

styles/migadu-webmail/catppuccin.user.css

Fixes a typo relating to a color for a disabled element and the background color for a specific variant of focused messages.

fix(migadu-webmail): misc

---

styles/duckduckgo/catppuccin.user.css

on duckduckgo when the page loads and before js finished loading the page have a `no-theme` class.
on unthemed duckduckgo this class makes the page follows the system theme
but with catppuccin that defaults to the light mode, which causes a light flash for a short time on load

fix(duckduckgo): light theme flash on page load

---

styles/youtube/catppuccin.user.css

Fixes the unthemed progressbar on shorts.
<details>
<summary>Preview</summary>
</details>

fix(youtube): shorts progress bar

---

styles/syncthing/catppuccin.user.css

Instead of the panel headers being `base`, like the background, they are set to `surface0`. This looks better imo.

fix(syncthing): make panel headers different from background

---

styles/youtube/catppuccin.user.css

Currently the icon in the LIVE badge on livestreams uses the `@text` color. This makes it hard to distinguish on the background of the badge, which uses `@accent-color`. This fix changes the icon to use the `@crust` color, matching it to the badge's text.

fix(youtube): properly color the "LIVE" badge icon

---

styles/chess.com/catppuccin.user.css

fixes the unthemed search bar
<details>
<summary>before & after</summary>
</details>

fix(chess.com): search bar

---

styles/duckduckgo/catppuccin.user.css

adds variables which fixes maps, aswell as disabled text
<details>
<summary>before & after</summary>
</details>

fix(duckduckgo): unthemed variables

---

styles/linkedin/catppuccin.user.css

I elected to do this rather then change the root var `--blue-60-a15` since chaning that var lead to breakages elsewhere.
closes https://github.com/catppuccin/userstyles/issues/1364#event-14544975805

fix(linkedin): hover buttons

---

flake.lock

meant to do this when deno was updated

chore(nix): bump inputs

---

styles/youtube/catppuccin.user.css

fix(youtube): live ring

---

styles/reddit/catppuccin.user.css

fixing the foreground color on some ui elements that use the brand color as background.
before:
after:

fix(reddit): text color on brand background

---

styles/tuta/catppuccin.user.css

Tuta now uses their actual brand colors in their app. This fixes the application of our accent colors.
I also adjusted the application to icons: The selected icon in the navbar now also uses the accent color.

fix(tuta): application of accent color

---

styles/deepl/catppuccin.user.css

Fixes poor contrast on highlighted text, hovered word and dictionary popout.
Closes #1149.
Before:
After:

fix(deepl): poor contrast on certain elements

---

styles/mastodon/catppuccin.user.css

fixed the background color on the getting started link items not matching the rest of the column.
before:
after:

fix(mastodon): getting-started links background colors

---

styles/wikipedia/catppuccin.user.css

Hello,
this pr fixes unthemed infobox subheaders, as the heading's text wasn't readable before
Here is an example site that has these classes: https://en.wikipedia.org/wiki/Flying_Witch
before:
now:

fix(wikipedia): missing infobox classes

---

styles/github/catppuccin.user.css

Jupyter notebook editor background is unthemed and codes are unreadable.
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/2ee04b1f-3383-44a9-8f3b-41d0c5f36480)|![image](https://github.com/user-attachments/assets/b8dcbbea-6e2e-49e5-924c-8ade8490b00c)|
This fix works for other 3 flavors as well.

fix(github): jupyter notebook editor background

---

styles/google-photos/catppuccin.user.css

fixes unthemed text :)
theres some text that only display when using google photos for the first time, which i fixed

fix(google-photos): text

---

styles/stack-overflow/catppuccin.user.css

fixes #1363 
fixed the contrast issue of notices on stack overflow
<p align="center">latte</p>
<p align="center">mocha</p>
<p align="center">latte</p>
<p align="center">mocha</p>

fix(stack-overflow): notices low contrast issue

---

styles/github/catppuccin.user.css

Fixes these loading throbbers:

fix(github): pull request check in progress indicator

---

styles/inoreader/catppuccin.user.css

Closes #1380 
Fixes the contrast issues of the sidebar on Inoreader
Latte + Mauve
Macchiato + Mauve
Macchiato + Sky
Latte + Mauve
Macchiato + Mauve
Macchiato + Sky

fix(inoreader): sidebar contrast issues

---

styles/chess.com/catppuccin.user.css

Themes the background of a random "coach nudge" modal that popped up,  and correctly themes the hover color of hovered icons in the toolbar.

fix(chess.com): hovered toolbar icons, coach nudge modal

---

styles/keybr.com/catppuccin.user.css

darken lesson key background colors
before:
after:

fix(keybr.com): darken lesson keys colors

---

styles/bsky/catppuccin.user.css

- themes the feeds/hashtag icon at the top of the timeline
- fix youtube/3rd party embeds being covered up
- fix image popout background not being transparent anymore

fix(bsky): some broken stuff and missing selectors

---

styles/hackage/catppuccin.user.css

* Colored the MathJax renders using proper filters instead of fully inverting the color.
* Fixed the synopsis toggle in Haddock using filters too.
* Themed older Haddock pages ([example](https://hackage.haskell.org/package/base-4.0.0.0/docs/Data-List.html)) and sources.

fix(hackage): color the synopsis toggle and older Haddock pages

---

styles/twitch/catppuccin.user.css

- custom username color #ffffff was displayed as Base color

fix(twitch): use proper username chat color

---

styles/twitch/catppuccin.user.css

- custom username color #ffffff was displayed as Base color in mod logs
- wrong text color was used in stream title and channel description on some channels

fix(twitch): use proper colors in mod logs, title and description

---

styles/github/catppuccin.user.css

fix(github): tooltip colors

---

styles/twitch/catppuccin.user.css

- Fixed wrong background color in video producer
- Fixed thumbnails in video producer

fix(twitch): video producer background and thumbnails

---

styles/duckduckgo/catppuccin.user.css

- new accent color variable
- tooltip background color
- menu item hover background
- code background
[example page](https://duckduckgo.com/?q=python+how+to+split+a+string)
search page:
before:
after:
ai chat:
before:
after:
- this border
- unexpanded lyrics gradient and explicit tag
[example page](https://duckduckgo.com/?q=pride+kendrick+lyrics)

fix(duckduckgo): unthemed elements

---

styles/google-photos/catppuccin.user.css

closes #1414 and themes the "move to archive" box

fix(google-photos): assorted changes

---

styles/twitch/catppuccin.user.css

- Themed [Twitch docs](https://dev.twitch.tv/docs/).

feat(twitch): twitch docs

---

styles/twitch/catppuccin.user.css

- Changed link color to match accent color
- Themed usercard tabs and added transparency to header overlay
- Fixed unthemed parts in [privacy center](https://twitch.tv/privacy)
- Fixed unreadable username highlight in top gifters/cheerers

fix(twitch): link color, usercard and privacy center fixes

---

styles/searxng/catppuccin.user.css

- Fixes the default domains not being detected, since `domain()` should not have `https://` in it.
- Fixes additional tweaks not working by explicitly specifying `when (@additions = 1)`

fix(searxng): default domains, additional tweaks

---

styles/twitch/catppuccin.user.css

- Fixed front page stream thumbnails
- Made channel points rewards cost more readable
- Themed shield mode tray highlight and icon
- Fixed wrong balloon title color
- Fixed wrong active color in [analytics](https://dashboard.twitch.tv/analytics)
- Fixed [stream alerts page](https://dashboard.twitch.tv/stream-alerts) text color
- Changed [stream manager](https://dashboard.twitch.tv/stream-manager) background color to mantle

fix(twitch): dashboard, channel points and shield mode fixes

---

scripts/userstyles.yml
styles/pronouns.cc/catppuccin.user.css
styles/pronouns.cc/preview.webp

feat(pronouns.cc): init

---

styles/picrew/catppuccin.user.css

Fixes a couple unthemed elements on the homepage (one of them only visible on mobile), and one on the search page.

fix(picrew): unthemed elements

---

styles/bsky/catppuccin.user.css

- fixed unthemed "cancel" button and icon buttons in create post modal
- fixed switches

fix(bsky): unthemed colors and switches 

---

styles/chatgpt/catppuccin.user.css

Fixes the background of the auth page

fix(chatgpt): auth page background

---

.stylelintrc.js
.vscode/settings.json
deno.json
scripts/lint/stylelint-custom/color-op-func-percentage.js
styles/advent-of-code/catppuccin.user.css
styles/anilist/catppuccin.user.css
styles/canvas-lms/catppuccin.user.css
styles/formative/catppuccin.user.css
styles/hoppscotch/catppuccin.user.css
styles/ichi.moe/catppuccin.user.css
styles/instagram/catppuccin.user.css
styles/lastfm/catppuccin.user.css
styles/linkedin/catppuccin.user.css
styles/mastodon/catppuccin.user.css
styles/reddit/catppuccin.user.css
styles/snapchat-web/catppuccin.user.css
styles/trinket/catppuccin.user.css
styles/whatsapp-web/catppuccin.user.css
styles/youtube/catppuccin.user.css

Adds a new rule, `require-color-op-func-percentage`, that requires the "amount" argument to [color operation](https://lesscss.org/functions/#color-operations) functions (e.g. `fade(<color>, <amount>)`) to be in percentage format - `<float or int>%`. This consistency makes these functions more readable, and can catch bugs. As you can see in the diff, there are many cases of `fadeout(@text, 0.8)`; people may think this 0.8 is out of 1, meaning 80%, but it is really just 0.8% (https://lesscss.org/less-preview/#eyJjb2RlIjoiYSB7XG4gIGNvbG9yOiBmYWRlb3V0KCMwMDAwMDAsIDAuOCk7XG59IiwiYWN0aXZlVmVyc2lvbiI6IjQuMi4wIiwibWF0aCI6InBhcmVucy1kaXZpc2lvbiIsInN0cmljdFVuaXRzIjpmYWxzZX0=). These very very tiny percentages should be corrected at some point as well.

feat(treewide): add require-color-op-func-percentage stylelint rule

---

styles/twitch/catppuccin.user.css

- Fixed [autohost channel list](https://dashboard.twitch.tv/settings/channel/auto-hosted-channels) background
- Fixed wrong background color in the [Activity](https://dashboard.twitch.tv/community/activity) tab
- Fixed new achievement balloon wrong background color
- Fixed wrong text color in [Stream Alerts](https://dashboard.twitch.tv/stream-alerts) tab when window is smaller
- Fixed wrong button color in unban requests
- Themed chat message timestamps and mod actions
- Fixed wrong text color in suspicious user banner
- Improved readability of chat emote preview
- Themed tables

fix(twitch): dashboard & mod view fixes

---

styles/bsky/catppuccin.user.css

- inappropriate hover in latte
- invisible text in latte
- icon contrast fix in mobile layout
- unthemed skeletons and thread lines

bsky: unthemed colors and some fixes

---

styles/github/catppuccin.user.css

Closes #1477. Applies the theme on the image diff iframes, which is in light mode by default FYI. Could add a separate toggle if warranted to change the theme for this part specifically?

fix(github): apply on image diffs

---

styles/wikipedia/catppuccin.user.css

added `.reference-text` to color the text that appears when you hover a citation link
Before:
After:

fix(wikipedia): text color of citation pop-up

---

styles/youtube/catppuccin.user.css

Live chat replay
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/daaa1c36-d598-45c0-a7c3-f88d3c41b48d)|![image](https://github.com/user-attachments/assets/8d3fb978-aa16-4e37-8ae1-f0a076496263)|
reproduction link: https://www.youtube.com/watch?v=khCQSqv6380
AI-generated video summary
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/de5399bb-9139-4720-8cf5-da6112b44ff7)|![image](https://github.com/user-attachments/assets/f11bc17d-fb22-4f27-afdf-929cb1b6cc1b)|
reproduction link: https://www.youtube.com/watch?v=JTRs1hSoclY

fix(youtube): texts of Live chat replay and AI-generated video summary

---

styles/youtube/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/1486
cherry picked from commit b530860fa2b524279f0973f0998595ccaf0fae17

fix(youtube): search bar

---

docs/USAGE.md

in docs/USAGE.md, under the "All Userstyles" step 3 refers to step 2 instead of step 1, I fixed it.

docs(USAGE.md): fix instruction step number

---

styles/youtube/catppuccin.user.css

Fixes shorts titles and views on the home page.
|Before|After|Normal Videos|
|-|-|-|
|![image](https://github.com/user-attachments/assets/c05bc3ae-00c0-48f0-af92-a02c8838415f)|![image](https://github.com/user-attachments/assets/958da0af-6362-492d-a01c-5101f6f05b10)|![image](https://github.com/user-attachments/assets/e70c2eb7-95af-4a7f-a0c4-d7cf08234b46)|

fix(youtube): shorts titles and views

---

README.md

We don't want to encourage new contributors to immediately become maintainers. We can suggest the idea of becoming a maintainer to active contributors when the time is right imo.

docs(README.md): remove mention of adding yourself as a maintainer

---

docs/SUMMARY.md
docs/guide/README.md
docs/guide/raw-color-values.md
docs/guide/rgb-values.md
styles/amplenote/catppuccin.user.css
styles/anilist/catppuccin.user.css
styles/chatgpt/catppuccin.user.css
styles/crates.io/catppuccin.user.css
styles/elk/catppuccin.user.css
styles/google-drive/catppuccin.user.css
styles/google-gemini/catppuccin.user.css
styles/google/catppuccin.user.css
styles/instagram/catppuccin.user.css
styles/lastfm/catppuccin.user.css
styles/lemmy/catppuccin.user.css
styles/mdbook/catppuccin.user.css
styles/namemc/catppuccin.user.css
styles/nitter/catppuccin.user.css
styles/ollama/catppuccin.user.css
styles/perplexity/catppuccin.user.css
styles/pronouns.cc/catppuccin.user.css
styles/pronouns.page/catppuccin.user.css
styles/proton/catppuccin.user.css
styles/snapchat-web/catppuccin.user.css
styles/stack-overflow/catppuccin.user.css
styles/substack/catppuccin.user.css
styles/trinket/catppuccin.user.css
styles/vercel/catppuccin.user.css
styles/whatsapp-web/catppuccin.user.css

Adds a new `hslify` mixin to match the functionality of the `rgbify` mixin (extract color values) - not used yet but I did needeto use it for https://github.com/catppuccin/userstyles/pull/1510. Also simplifies the existing `rgbify` mixin and inserts it in places where we should be using it (_technically_ might not be the exact same since the comma vs space separated rgb syntax is weird, will have to check).

refactor(treewide): cleanup and use rgbify mixin

---

styles/youtube/catppuccin.user.css

Fixes the unstyled 'How this was made' section in the description box.
| **Before**                    | **After**                 |
| ----------------------------- | ------------------------- |
| ![image](https://github.com/user-attachments/assets/a3fb26b0-843e-4d60-961c-51bfaa154b74) | ![image](https://github.com/user-attachments/assets/9d0d4919-c21b-475d-84d3-8abe54248507) |

fix(youtube): description how this was made section

---

.github/workflows/ci.yml

Workflow couldn't run the full script because it wasn't authenticated like the other workflow involving GH API / teams was, this should do the trick.

ci(ci.yml): pass USERSTYLES_TOKEN secret to access gh api

---

.vscode/settings.json

Not sure why I didn't do this before lol. I forgot to add Yaml to the list of languages and thought we might as well just do everything in case I missed another and for the future.

chore(.vscode/settings.json): set deno as default formatter project-wide

---

styles/hackage/catppuccin.user.less

| --- | --- |
| ![CleanShot 2024-12-31 at 20 38 08](https://github.com/user-attachments/assets/2176cc57-34b7-45d2-8a22-c6d2e9958ddf) | ![CleanShot 2024-12-31 at 20 37 26](https://github.com/user-attachments/assets/334b7285-e6fd-4ea4-9f1b-d8bb012d2edc) |

fix(hackage): make headings text

---

styles/github/catppuccin.user.less

They changed the inline hex values from uppercase to lowercase after #1396 lol. This just makes it case insensitive, just checked on the last merged PR + commit.

fix(github): github actions check running indicator

---

styles/microsoft-word/catppuccin.user.less

This adds an option to toggle the theme on the actual page.
Closes #1466 
Disabled:
Enabled:

feat(microsoft-word): add apply to document option

---

styles/hackage/catppuccin.user.less

Adds a properly themed SVG for the synopsis toggle in Haddock pages ([example](https://hackage.haskell.org/package/text-2.1.2/docs/Data-Text.html)).

feat(hackage): use an svg for the synopsis toggle

---

scripts/lint/main.ts

This regex is kinda stupid lol.

fix(scripts/lint): userstyle names can include dashes

---

styles/github/catppuccin.user.less

See https://github.com/uncenter/flake/blob/main/.github/assets/nix.svg, the background around the image was previously unthemed.

fix(github): view image file background

---

styles/twitch/catppuccin.user.less

Fixes unthemed AutoMod alerts in chat.
Before | After
---------- | ----------

fix(twitch): automod message alert

---

styles/chatgpt/catppuccin.user.less

Fixes the backgrounds of limit alert and middle pricing panel (which is on the upgrade plan page)
|----------|---------|
|![image](https://github.com/user-attachments/assets/fc4ba007-5ba0-47a5-ad62-fe409cccb6aa)|![image](https://github.com/user-attachments/assets/a26ca0eb-2d03-430a-9e64-531b4f5bf16f)|
|![image](https://github.com/user-attachments/assets/4e96b1e0-07b4-4887-a028-de33adc2280a)|![image](https://github.com/user-attachments/assets/876ace73-9515-435b-a777-75bf0f39f468)|

fix(chatgpt): limit alert bg and middle pricing panel

---

styles/github/catppuccin.user.less

Just themes the whole domain, I don't think this will cause any issues.

fix(github): adjust matcher from `regexp` to generic `domain`

---

README.md
scripts/generate/readme-repo.ts
scripts/generate/templates/userstyle.md

Importantly this removes the note about adding yourself as a maintainer - I don't think we want to encourage this. I also decided to change the emoji from the foreboding caution gate emoji to this more fitting broken(?) heart emoji, in line with the current/past maintainers emojis, because userstyles that don't have maintainers can still very well be perfectly fine/working correctly despite that.

docs: improve unmaintained notes & emojis in READMEs

---

styles/gmail/catppuccin.user.less

Updates the class for header which fixes the search bar input background and header icons (top-right).
|----------|---------|
|![image](https://github.com/user-attachments/assets/eb28fe58-1a46-49e1-ba77-bb4fa7686979)|![image](https://github.com/user-attachments/assets/0b232f39-8893-4085-942a-cbd527db5ae1)|
|![Screenshot 2025-01-15 195207](https://github.com/user-attachments/assets/5a0f4c5d-0dc2-4f4a-bc7b-ea1a95302810)|![Screenshot 2025-01-15 204040](https://github.com/user-attachments/assets/d674ed79-90a5-4f27-9300-876ddf8e9a28)|
|![image](https://github.com/user-attachments/assets/517d2b70-de85-45aa-a16b-c9dbf9884966)|![image](https://github.com/user-attachments/assets/f8cf8aaf-936d-4c6a-bf0f-ed04c1251734)|

fix(gmail): search bar and header icons

---

styles/github/catppuccin.user.less

Looks like it was recently updated to use the new CSS variable naming scheme adopted on the main site last year, so it works like a charm and only needs this one old CSS variable name to be set (for code blocks and presumably other things).

feat(github): docs.github.com

---

styles/instagram/catppuccin.user.less

this fix Play, Pause and Timer background colors and closes #1590.
incoming voice clip:
- Before:
- After:
outgoing voice clip:
- Before:
- After:
voice clip recording:
- Before:
- After:

fix(instagram): voice clip

---

styles/ghostty.org/catppuccin.user.less

Themes the terminal title bar on the [home page](https://ghostty.org). (Visible only on Linux user-agent)
| ------- | ------ |
| ![2025-01-28-010932_hyprshot](https://github.com/user-attachments/assets/e79e0f52-8554-4c60-8832-729c0735db29) | ![2025-01-28-010916_hyprshot](https://github.com/user-attachments/assets/4e6e57ae-4394-48b3-bae9-850f647b30ad) |

fix(ghostty.org): adwaita terminal title bar

---

styles/youtube/catppuccin.user.less

Fixing an error caused by my previous PR #1592. I mistakenly removed `background: @accent;` from a section, thinking it was redundant. Apologies for the oversight.
|----------|---------|
|![image](https://github.com/user-attachments/assets/73b10e15-5d4d-4201-bb9d-d38e49d40542)|![image](https://github.com/user-attachments/assets/9a22c025-8bc5-4e4d-8bed-2cc7b7e8ffe7)|

fix(youtube): toggle button color in video options

---

scripts/userstyles.yml
styles/gleam.run/catppuccin.user.less
styles/gleam.run/preview.webp

I don't think we can call this just `gleam` since there is already a `catppuccin/gleam` and I don't want to intentionally create more port "duplicates".

feat(gleam.run): init

---

styles/wikipedia/catppuccin.user.less

Closes #1613. Leaving as a draft for now since I'm pretty sure I had this set for a reason when I rewrote it (but I can't find what the issue was now).

fix(wikipedia): remove default anchor element color

---

styles/stack-overflow/catppuccin.user.less

Makes visited links use accent color. 
| Before  | After |
| ------------- | ------------- |
| ![2025-01-25-221026_hyprshot](https://github.com/user-attachments/assets/7f8bca4b-361b-4f58-97b6-f7b1db05f116) | ![2025-01-25-220729_hyprshot](https://github.com/user-attachments/assets/5d126851-60ea-4651-875a-ba3de441d7f9) |

fix(stack-overflow): follow style guide for links

---

styles/chatgpt/catppuccin.user.less

The message input box background color should be `@surface0`. As far as I know, it was previously set correctly to `@surface0`.
|---|---|
|![image](https://github.com/user-attachments/assets/40176148-65b2-4967-b3c8-ee90366290c1)|![image](https://github.com/user-attachments/assets/edfc06b6-26a3-424a-9e10-c905db6bcf74)|

fix(chatgpt): message input box background

---

styles/twitch/catppuccin.user.less

- Themes share buttons in clip editor
- Themes timeline in clip editor
- Themes stream thumbnail border (when streaming with Guest Star)
- Fixes timestamp balloon text color
- Fixes highlight in automod queue
- Fixes pinned message shadow
- Fixes followed channels background color on focus
- Fixes stream manager stats background color
- Fixes Guest Star circle buttons
- Fixes poll winner text color
- Fixes footer link text color
- Fixes button background color in channel rewards *Learn more* section
- Makes primary button a little darker on hover
- Changes alt text color to match Twitch

fix(twitch): misc

---

styles/chatgpt/catppuccin.user.less

Fixes the message input box in temporary chat option
|---|---|
|![image](https://github.com/user-attachments/assets/30f747ba-9f71-4dd8-a43e-9d862fabe1e3)|![image](https://github.com/user-attachments/assets/3f1c83e4-f4b7-49a4-8b10-70921af993ed)|

fix(chatgpt): chat input box background

---

styles/instagram/catppuccin.user.less

fixing the `Next` and `Go back` svg buttons fill color for reels post

fix(instagram): prev/next button svgs

---

styles/brave-search/catppuccin.user.less

Themes the "Ask a follow-up question" text field.
- [v] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).

fix(brave-search): theme ask a follow-up question field 

---

styles/seventv/catppuccin.user.less

Themes chat mod buttons in the extension.
| ------- | ------ |
| ![2025-03-02-163651_hyprshot](https://github.com/user-attachments/assets/92b42b6c-2a33-4133-87e0-a8fd9d7541b7) | ![2025-03-02-163744_hyprshot](https://github.com/user-attachments/assets/0f1b612f-f48c-4fce-af8d-ff4412e6a89a) |

fix(seventv): chat mod button color

---

styles/pypi/catppuccin.user.less

- green checkmark next to "verified details"
- subtext under "unverified details
- adds the alternating colors back to tables

fix(pypi): various

---

styles/pinterest/catppuccin.user.less

- **Fix hover state (`--color-background-button-tertiary-hover`):**
- Before:
- After:
- **Fix opened state:**
- Before:
- After:
- **Fix pin link background color:**
- Before:
- After:
- **Fix issue caused by changing `--color-text-dark` (affecting `one-bar-pill` text color):**
- Before:
- After:
- **Fixed similar issues on `closeupActionBar` for pins.**
- **Addressed all possible cases for small white rectangles issue.**
---

fix(pinterest): variables and pin actions

---

styles/chess.com/catppuccin.user.less

fix(chess.com): arrow and square highlights

---

styles/pinterest/catppuccin.user.less

Themes the bouncing pinterest logo you can see briefly when (re)loading the tab.

fix(pinterest): loading screen logo

---

styles/wikipedia/catppuccin.user.less

Fixes #1684. Previously the filter was only disabled on automatic ("os") appearance, now it is also disabled for dark ("night") appearance.

fix(wikipedia): disable logo invert filter on dark appearance

---

styles/wikipedia/catppuccin.user.less

Noticed in https://github.com/catppuccin/userstyles/issues/1684#issuecomment-2763798809 that Wikipedia's login button now takes you to the auth.wikimedia.org domain for authentication. The userstyle is capable of theming the page entirely already, so this just adds the domain to the list of applicators.

fix(wikipedia): apply on new auth domain

---

styles/wikipedia/catppuccin.user.less

MediaWiki only applies some overrides (involving inheriting colors and using variables) on dark and automatic appearance settings, leaving broken elements with the light appearance. This copies those overrides and applies them all the time, which should fix the issue outlined in https://github.com/catppuccin/userstyles/issues/1684#issuecomment-2763830548.
I also applied to small fixes to a variable and a box border that I noticed while investigating.

fix(wikipedia): misc

---

styles/cinny/catppuccin.user.less

Makes links blue instead of rosewater.

fix(cinny): blue links

---

styles/pinterest/catppuccin.user.less

Updates some syntax in the Pinterest userstyle to avoid errors the Deno formatter was throwing.

fix(pinterest): avoid formatter syntax errors

---

styles/snapchat-web/catppuccin.user.less

`web.snapchat.com` appears to redirect to `snapchat.com/web` now:
```sh
$ curl https://web.snapchat.com hv
* Host web.snapchat.com:443 was resolved.
* IPv6: (none)
* IPv4: 34.149.46.130
*   Trying 34.149.46.130:443...
...
> GET / HTTP/2
> Host: web.snapchat.com
> User-Agent: curl/8.12.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 301 
...
* Connection #0 to host web.snapchat.com left intact
Moved Permanently. Redirecting to https://www.snapchat.com/web/%   
```

fix(snapchat-web): change domain

---

styles/hackage/catppuccin.user.less

Looks like most (if not all) new packages have their documentations hosted on `hackage-content.haskell.org` now, so I added that to the domains ([example link](https://hackage-content.haskell.org/package/containers-0.8/docs/Data-Map.html)). Maybe related to https://github.com/haskell/hackage-server/pull/1379 or something.
Other than that, new packages have inline code blocks (finally), and there is a **single** package I came across that has a table of contents in the index so I made its background match the style of the original Hackage:
| example | old | fixed |
| :-----: | :-: | :---: |
| [link](https://hackage.haskell.org/package/base-4.21.0.0/docs/Data-List.html) | ![An inline code block in wrong colors.](https://github.com/user-attachments/assets/d6c28794-7189-47de-8fbf-ec5a75c08cba) …

fix(hackage): new subdomain and inline code

---

styles/stack-overflow/catppuccin.user.less

askubuntu.com has repeating gray dots in its background:
The current userstyle does not take these into account. This results in a horrible contrast throughout the entire background:
This fix removes the dots (which are implemented as a repeating 4x4 pixel image), setting the background-image of the body to `none` which does not affect the normal stackoverflow website but removes the pattern on askubuntu.com:

fix(stack-overflow): fix background on askubuntu.com

---

styles/youtube/catppuccin.user.less

Fixes overlay background on youtube thumbnails when downloading a video!
Original:
Before:
After:

fix(youtube): changed fade of --yt-spec-themed-overlay-background

---

styles/wikipedia/catppuccin.user.less

Leads to image backgrounds like at https://en.wikipedia.org/wiki/Chernobyl_New_Safe_Confinement#Structural_design not having contrast. I think the default (#fff or something) is good, this change doesn't seem to affect anything else.

fix(wikipedia): unset `--background-color-base-fixed` var

---

styles/youtube/catppuccin.user.less

Fixes black header, closes #1533 
It's seems like a new `div#frosted-glass` was introduces on main page.
The old one is still required for other pages such as the history.

fix(youtube): new ui header background

---

styles/youtube/catppuccin.user.less

Makes recoloring SponsorBlock segments (from #1722) optional.

feat(youtube): optional sponsorblock recoloring

---

styles/canvas-lms/catppuccin.user.less

- Reorganizes button styling to not rely on autogenerated classnames as much
- Mixins are used for easier organization
- Some buttons that became unstyled with recent canvas css changes will now stay styled (hopefully)
- Many buttons now look better/react properly to hover (modals, inbox, discussions, etc)
- Revises tooltip styling
- Styles the new file upload component on assignment submission
- misc:
- Tooltip arrows are the proper color
- Checkboxes are styled
- Some icons are fixed
(It's pretty late for me but if preview screenshots are wanted, or if this PR should be split into pieces, I can do that later)
another thing to resolve: how should outlines on focused buttons/links/etc like these be colored:
in canvas I think they just use blue for everything. since in this userstyle we …

fix(canvas-lms): buttons & misc

---

styles/youtube/catppuccin.user.less

fixes unthemed streaming indicator in sidebar.

fix(youtube): sidebar streaming indicator

---

styles/chatgpt/catppuccin.user.less

Fixes unthemed sidebar header backgrounds
|---|---|
|![image](https://github.com/user-attachments/assets/9d4b34a1-fecf-4388-a60c-d899f7708547)|![image](https://github.com/user-attachments/assets/2a6fb59b-ed29-42e3-915e-be63161e1556)|

fix(chatgpt): sidebar headers bg

---

styles/nixos-manual/catppuccin.user.less

they moved nix-darwin to a org.

chore(nixos-manual): update nix-darwin url

---

styles/cinny/catppuccin.user.less

Uses the proper Catppuccin port source for Prism syntax highlighting (https://github.com/catppuccin/userstyles/blob/main/docs/guide/syntax-highlighting.md) :)
| --- | --- |
| ![CleanShot 2025-05-17 at 07 46 35](https://github.com/user-attachments/assets/c4f72d31-4529-4a1a-924d-4b79e6fa2218) | ![CleanShot 2025-05-17 at 07 45 45](https://github.com/user-attachments/assets/0e0e8548-55f8-45fa-8baa-bdc7ef03b61b) |

fix(cinny): prism syntax highlighting

---

styles/vikunja/catppuccin.user.less

This PR fixes some small things and updates to latest Vikunja version. Fixes includes:
- Emoji picker
- Calendar icon having a background
- Delete button changing color to wrong red when hovering
- Hovering color on "Edit Views" page
- Inline code
- Block codes
- Quotes on comments
- Emoji reactions

fix(vikunja): assorted updates

---

styles/github/catppuccin.user.less

Closes #1778 and supersedes #1779 (closes #1779).
As @sillowww [pointed out in Discord](https://discord.com/channels/907385605422448742/1030437391607025765/1380647724617306164), the issue can be reproduced on the "sync with system" appearance mode, even more specifically when you have prefers-color-scheme: dark. In that one specific scenario, GitHub's selectors target `data-color-mode][data-color-mode="auto"]`, unlike their light selectors and our userstyle's selectors that use just `[data-color-mode="auto"]`.
This fix copies their extra/redundant selector to increase the specificity and seems to correct the issue on my end.

fix(github): higher specificity of auto/system theme selector

---

styles/claude/catppuccin.user.less

Claude uses both `pre` and `div` elements to display code blocks. Previously with the `pre.code-block__code` selector we were only changing the color of `pre` code blocks. This update makes sure `div` code blocks are selected as well.

fix(claude): consistent code blocks

---

docs/tips-and-tricks/see-changes-in-real-time.md

Updates the fragment to match where we want readers to look.

docs(tips-and-tricks/see-changes-in-real-time): update stylus wiki link

---

styles/youtube/catppuccin.user.less

This should fix #1766 as it has also been bothering me for a while.
It also adds a new settings called `systemTheme` that probably almost no one would find useful but its another thing that bothers me. Whenever you change your system theme from light/dark, you wont see it until you refresh the page or navigate to another one. Enabling this setting should follow the system theme. I think it could interfere if you have a preferred theme selected on youtube other than `Device theme`. Thats why its disabled by default.

fix(youtube): player option tooltips

---

styles/arch-wiki/catppuccin.user.less

It uses some variables for automatic light/dark mode.

fix(archwiki): respect site-configured color scheme

---

styles/bsky/catppuccin.user.less

Entirely my bad, and apologies for the extremely tiny PR.
My previous fix contained a style that used `border:` instead of `border-color:` and it's triggering ci lint failures on other userstyles. Not super high priority but will be annoying nontheless.

chore(bsky): lint

---

styles/lichess/catppuccin.user.less

This PR fixes unthemed drawn annotations (piece circles, arrows), and fixes unthemed local eval bar and threat analysis button.
Due to the piece circles and arrows being SVGs (and my lack of CSS/LESS experience), I'm not sure if the approach I used is the most optimal, feel free to suggest alternatives.
Arrows and piece circles example:
Themed local eval bar:
Threat eval bar and button:

feat(lichess): add theme to drawn annotations, local eval bar, and threat analysis button

---

scripts/generate/main.ts

Marks the whole `lib/` folder as owned by staff, since library modules are intended to be used by more than one userstyle they have larger ranging consequences than just a single userstyle would.

chore(lib): mark staff as codeowners

---

scripts/userstyles.yml

Add WalkQuackBack as maintainer for google-gemini
In preperation for library PRs

chore(google-gemini): add `WalkQuackBack` as maintainer

---

styles/google-photos/catppuccin.user.less

Fixes the root target selector for Google Photos.

fix(google-photos): root target selector

---

docs/src/content/docs/contributing/index.md

The (already existing) `## Authoring userstyles` section is messy. I can't figure out how to structure it in a way where it is meaningfully located. The assessing websites part should probably be on userstyles creation page?

docs(contributing): clarify lint command, automated versioning

---

docs/src/content/docs/contributing/guides/images-and-svgs.md

Moves the formerly titled "Non-SVG images or many `<img>` elements with external SVGs" section to the top, now titled "Monochrome `<img>` elements". Since the filter palette and variables are included by default with the standard library, this is now by far the easiest and simplest way for many usecases.
In the "SVGs as `background-image`s" section, I've split the obtaining of the SVG contents into two subsections depending on the original format. This includes a new subsection on "Inlined SVG data URL"s.
An additional note about single quotes when pasting SVG contents, some wording changes.

docs(guides/images-and-svgs): monochrome images, inlined svg data urls

---

styles/whatsapp-web/catppuccin.user.less

Increases the contrast for WhatsApp web chat outgoing, encryption and buisness bubbles.

fix(whatsapp-web): contrast rebalancing

---

styles/lichess/catppuccin.user.less

This PR fixes the inverted colors for the pieces on latte and also fixes the queen piece svg.
It also makes some smaller minor changes (slight changes to piece colors and removing weird thick lines on knight and king).
Closes: #1890

fix(lichess): inverted piece colors and black queen piece
