styles/nitter/catppuccin.user.css
styles/nixos-search/catppuccin.user.css
styles/reddit/catppuccin.user.css

Seems some of the `updateURL` links were still missed.

fix: ensure correct `updateURL` links

---

styles/deepl/catppuccin.user.css
styles/ichi.moe/catppuccin.user.css

refactored to less
Convert the port to LESS as discussed in https://github.com/catppuccin-rfc/userstyles/discussions/20 and https://github.com/catppuccin-rfc/userstyles/issues/21

refactor: convert to less

---

README.md

- `catppuccin.user.css` - all stylus code.
- `mocha.webp`, `macchiato.webp`, `frappe.webp` and `latte.webp` - individual screenshots of the themed website, in all 4 Catppuccin flavors.
- `catwalk.webp` - image of all individual screenshots stitched together, generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

docs: fix silly dot and broken link on the readme

---

README.md

As title
/cc @sgoudham @nekowinston

docs: discussions disabled

---

.github/ISSUE_TEMPLATE/userstyle.yml
src/generate/templates/userstyle-issue.yml
styles/anilist/catppuccin.user.css
styles/deepl/catppuccin.user.css
styles/elk/catppuccin.user.css
styles/ichi.moe/catppuccin.user.css
styles/lastfm/catppuccin.user.css
styles/libreddit/catppuccin.user.css
styles/mastodon/catppuccin.user.css
styles/modrinth/catppuccin.user.css
styles/nitter/catppuccin.user.css
styles/nixos-search/catppuccin.user.css
styles/proton/catppuccin.user.css
styles/tutanota/catppuccin.user.css
styles/twitch/catppuccin.user.css
styles/wikiwand/catppuccin.user.css
styles/youtube/catppuccin.user.css
template/catppuccin.user.css

I'm sorry about all the pings, code owners, I just wanted to make sure we have unified spelling with catppuccin/catppuccin here.

chore: en-GB -> en-US

---

src/userstyles.yml
styles/crowdin/assets/catwalk.webp
styles/crowdin/assets/frappe.webp
styles/crowdin/assets/latte.webp
styles/crowdin/assets/macchiato.webp
styles/crowdin/assets/mocha.webp
styles/crowdin/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/60

feat: crowdin

---

src/userstyles.yml
styles/whatsapp-web/assets/catwalk.webp
styles/whatsapp-web/assets/frappe.webp
styles/whatsapp-web/assets/latte.webp
styles/whatsapp-web/assets/macchiato.webp
styles/whatsapp-web/assets/mocha.webp
styles/whatsapp-web/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/52

feat: add whatsapp web

---

src/userstyles.yml
styles/homepage/assets/catwalk.webp
styles/homepage/assets/frappe.png
styles/homepage/assets/latte.png
styles/homepage/assets/macchiato.png
styles/homepage/assets/mocha.png
styles/homepage/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/50

feat: add homepage

---

src/userstyles.yml
styles/invokeai/assets/catwalk.webp
styles/invokeai/assets/frappe.webp
styles/invokeai/assets/latte.webp
styles/invokeai/assets/macchiato.webp
styles/invokeai/assets/mocha.webp
styles/invokeai/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/59

feat: add invokeai

---

src/userstyles.yml
styles/advent-of-code/assets/catwalk.webp
styles/advent-of-code/assets/frappe.webp
styles/advent-of-code/assets/latte.webp
styles/advent-of-code/assets/macchiato.webp
styles/advent-of-code/assets/mocha.webp
styles/advent-of-code/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/61

feat: add advent of code

---

src/userstyles.yml
styles/ecosia/assets/catwalk.webp
styles/ecosia/assets/frappe.webp
styles/ecosia/assets/latte.webp
styles/ecosia/assets/macchiato.webp
styles/ecosia/assets/mocha.webp
styles/ecosia/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/54

feat: add ecosia

---

styles/github/catppuccin.user.css

In regards to https://github.com/catppuccin/userstyles/issues/21
closes https://github.com/catppuccin/userstyles/issues/90

refactor: convert github to less

---

styles/modrinth/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/95

fix: for https://github.com/catppuccin/userstyles/issues/95

---

styles/deepl/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/87
closes https://github.com/catppuccin/userstyles/issues/88

fix: deepl

---

styles/twitch/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/98
(sorry about the other pr, wrong branch)

fix(twitch): enforce userstyles practices & overlay text

---

styles/libreddit/assets/catwalk.webp
styles/libreddit/assets/frappe.webp
styles/libreddit/assets/latte.webp
styles/libreddit/assets/macchiato.webp
styles/libreddit/assets/mocha.webp

In relation to https://github.com/catppuccin/userstyles/issues/69

fix: update pictures for libreddit

---

styles/chatgpt/catppuccin.user.css

fix(chatgpt): fix selector for conversations

---

styles/proton/catppuccin.user.css

Before:
After:
Reference(Default Carbon):

fix(proton): ring and active color

---

styles/mastodon/catppuccin.user.css

Changes: 
- add theming for emoji picker
- add theming for glitch soc

fix(mastodon): fill unthemed sections

---

styles/github/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/93
closes https://github.com/catppuccin/userstyles/issues/91
closes https://github.com/catppuccin/userstyles/issues/142

fix(github): fix unthemed sections

---

styles/proton/catppuccin.user.css

fix(proton): lighten colors on latte

---

styles/proton/catppuccin.user.css

fix(proton): tooltip color

---

src/userstyles.yml
styles/chatreplay/assets/catwalk.webp
styles/chatreplay/assets/frappe.webp
styles/chatreplay/assets/latte.webp
styles/chatreplay/assets/macchiato.webp
styles/chatreplay/assets/mocha.webp
styles/chatreplay/catppuccin.user.css

[ChatReplay](https://chatreplay.stream) adds a twitch chat to VODs
I added another param for `#catppuccin` called `platform` to apply separate styles to the chatbox and website.
template.

feat: add ChatReplay

---

styles/mastodon/catppuccin.user.css

fixes https://github.com/catppuccin/userstyles/issues/159

fix: now works on default firefox

---

styles/modrinth/catppuccin.user.css

Made the userstyle work with www.modrinth.com and staging.modrinth.com too.

fix(modrinth): Userstyle did not work with some urls

---

styles/anilist/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/165

fix(anilist): overylay text

---

styles/github/catppuccin.user.css

All changes:
- Turned the top loading bar to the accent color
- Turned the tab selection bottom-border to the accent color
- Fixed wrong colors of folder up selection within repo folders
- Fixed buttons and their dropdowns in code explorer not being in line with the theme
- Fixed search bar in code explorer not being in line with the theme

fix(github) - Fixed missing work on the code explorer and changed two small ui pieces to accent color

---

.github/workflows/generate.yml
.github/workflows/maintainers.yml

Please read the commit descriptions for an overview of the changes.

ci: ensure actions are fork-friendly

---

src/userstyles.yml

"Social" doesn't really work well for them

(youtube,invidious,twitch): fix categories

---

styles/proton/catppuccin.user.css

Adds catppuccin colors to the upgrade-button

fix(proton): style upgrade button

---

.github/workflows/generate.yml

Reverts catppuccin/userstyles#196

Revert "ci: call `readme.yml` in `catppuccin/catppuccin`"

---

styles/tutanota/catppuccin.user.css

the world if Tutanota used CSS variables

fix(tutanota): color replacements for most UI elements

---

styles/reddit/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/185
after fix:

fix(reddit): codeblocks

---

styles/twitch/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/203

fix(twitch): fix colouring

---

styles/elk/catppuccin.user.css

Based it off of https://github.com/catppuccin/userstyles/blob/main/styles/twitch/catppuccin.user.css.

feat(elk): theme select for light/dark mode

---

styles/twitch/catppuccin.user.css

fix(twitch): Make text readable when using theater mode

---

.github/workflows/format.yml

ci: fix prettier format

---

styles/twitch/catppuccin.user.css

<details>
<summary>`Is video buffering?` warning</summary>
</details>
<details>
<summary>`Includes paid promotion` label</summary>
</details>
<details>
<summary>Raiding popup</summary>
</details>
<details>
<summary>`Predict with Channel Points` popup</summary>
</details>
<details>
<summary>Poll popup</summary>
</details>
<details>
<summary>???</summary>
</details>
<details>
<summary>Gifting sub popup</summary>
</details>

fix(twitch): Make text readable in miscellaneous sections

---

src/userstyles.yml

closes https://github.com/catppuccin/userstyles/issues/220

fix(meta): youtube usage note

---

styles/twitch/catppuccin.user.css

<details>
<summary>Metadata</summary>
</details>
<details>
<summary>Seekbar</summary>
</details>

fix(twitch): Make text in vods readable

---

styles/twitch/catppuccin.user.css

<details>
<summary>VOD title</summary>
</details>

fix(twitch): Make text on offline screen readable

---

styles/proton/catppuccin.user.css

updated for the newly added properties in the base theme

fix(proton): update styles

---

styles/chatgpt/catppuccin.user.css

I burnt my retina out for the sake of this i hope everyone is please.
closes https://github.com/catppuccin/userstyles/issues/213

fix(chatgpt): lightmode improvments

---

styles/github/catppuccin.user.css

additional fixes for https://github.com/catppuccin/userstyles/issues/231

fix(github): ignore homepage / not loggedin

---

styles/twitch/catppuccin.user.css

<details>
<summary>Age selector</summary>
</details>

fix(twitch): Make text on front page readable

---

styles/twitch/catppuccin.user.css

fixup https://github.com/catppuccin/userstyles/pull/241

fix(twitch): Update pinned message background color

---

styles/twitch/catppuccin.user.css

* Popup to claim moment does not show up when chat is hidden, so nothing to fix here
* Moments are getting [deprecated](https://twitter.com/TwitchSupport/status/1697299099140157736) on 2023/10/05
<details>
<summary>Viewer Card</summary>
</details>

fix(twitch): Make text in viewercard readable

---

styles/youtube/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/248

fix(youtube): contrast issues

---

styles/youtube/catppuccin.user.css

follows https://github.com/catppuccin/userstyles/pull/249#issuecomment-1745722258

fix(youtube): readablity

---

styles/twitch/catppuccin.user.css

fixed css colors on the login popup

Color stuff on the "Login" popup

---

styles/twitch/catppuccin.user.css

https://github.com/catppuccin/userstyles/pull/253#discussion_r1349541471

text -> @text

---

src/userstyles.yml

Following https://github.com/catppuccin/userstyles/pull/260, we noticed that there was a lack of clarity behind some of the instance based userstyles, this PR hopes to address that and improve on the current situation.

docs: improve instance based documentation

---

styles/planet-minecraft/catppuccin.user.css

odd-index notifs are now properly themed with catppuccin.

fix(planet-minecraft): properly theme notifs

---

src/generate/syncMaintainers.ts

This Pull Request ensures that the `syncMaintainers` GitHub action does not send team invites to all collaborators but only the current maintainers.

ci: sync only the `current-maintainers`

---

styles/youtube/catppuccin.user.css

Closes https://github.com/catppuccin/userstyles/issues/274

feat(yt): improve scroll bar

---

styles/planet-minecraft/catppuccin.user.css

this pr:
- fixes the server action buttons
- removes the "piss yellow" navigation selection color when on a server page in favor of the selected accent
a pr will come soon to iron out all the accent issues

fix(planet-minecraft): better servers page

---

styles/mastodon/catppuccin.user.css

add the domain https://wetdry.world to the mastodon userstyle

add wetdry.world to mastodon

---

styles/chatgpt/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/286

fix(chatgpt): unthemed main section

---

styles/canvas-lms/catppuccin.user.css

Closes #179. Not a perfect fix but just restores it to a useable state.

fix(canvas-lms): broken file preview bug

---

styles/pinterest/catppuccin.user.css

A lot of fixes for a lot of stuff I missed.
I'll keep this as a draft for a day to see if I can find anything else.

fix(pinterest): a lot of fixes

---

src/userstyles.yml
styles/linkedin/assets/catwalk.webp
styles/linkedin/assets/frappe.webp
styles/linkedin/assets/latte.webp
styles/linkedin/assets/macchiato.webp
styles/linkedin/assets/mocha.webp
styles/linkedin/catppuccin.user.css

Social networking site
template.

feat(linkedin): init

---

styles/youtube/catppuccin.user.css

Why yt, why do you keep hardcoding these values.
What reason do you have.
You laterally have vars for this.
The buttons have not even changed so why use hardcoded vaules.

fix(yt): why so many buttons

---

.github/workflows/format.yml

pull changes before pushing the formatted code to fix an error where the formatter would fail

fix(ci/format): pull changes before pushing the formatted code

---

styles/github/catppuccin.user.css

Some fixes for GitHub tree mode and fix for archived repo notification not having the right background

fix(github): various fixes

---

styles/youtube/catppuccin.user.css

The notification bell and bell next to sub button also theme YouTube's feature banner

fix(yt): various fixes

---

styles/instagram/catppuccin.user.css

before: 
after: ![image](https://github.com/catppuccin/userstyles/assets/29279972/490ee802-8217-4b8f-bb08-3357416a87c8)

Fix Verified Badge Coloring

---

template/catppuccin.user.css

@isabelroses some of those changes we discussed.

chore(template): update

---

styles/youtube/catppuccin.user.css

fix(yt): Fix a few buttons

---

styles/tutanota/catppuccin.user.css

Closes #319 by changing the URL to `app.tuta.com`.

fix(tutanota): update domain

---

styles/reddit/catppuccin.user.css

Finally convert reddit to less, and start theming of the new beta theme.
Closes https://github.com/catppuccin/userstyles/issues/21

refactor(reddit): move to less

---

styles/chatgpt/catppuccin.user.css

Fixes issues with the new UI
Adds accent colour options
Closes #303

fix(chatgpt): fix new ui + accent colours

---

styles/youtube/catppuccin.user.css

fix(yt): use base for more backgrounds

---

.github/workflows/format.yml
.prettierignore
.prettierrc

Now that reddit is using Less (#333) we can enable prettier for all userstyles, and `src` moved to `scripts`.

style: tweak prettier settings

---

scripts/generate/labels.ts
scripts/generate/main.ts
scripts/generate/readme-repo.ts
scripts/generate/readme-styles.ts
scripts/generate/templates/userstyle.md
scripts/lint/file-checker.ts
scripts/lint/main.ts
scripts/lint/metadata.ts
scripts/lint/stylelint.ts
scripts/sync-maintainers/main.ts
scripts/types/mod.ts

build: minor fixes

---

.github/workflows/deno-check.yml
.github/workflows/generate.yml
.github/workflows/lint.yml
.github/workflows/maintainers.yml

I worked on an improved [`setup-deno`](https://github.com/nekowinston/setup-deno) action so caching should be more consistent with this one.

ci: use `nekowinston/setup-deno` for caching

---

styles/brave-search/catppuccin.user.css

Fixes unthemed elements on settings page

fix(brave): settings page

---

styles/invidious/catppuccin.user.css

Reworks Invidious & styles bits that were unthemed.

feat(invidious): rework & update

---

styles/youtube/catppuccin.user.css

fix(youtube): overlay effect, used on clips mainly

---

docs/userstyle-creation.md

Just a tiny broken link in the creation guide

fix(docs): broken link to userstyle.yml in userstyle-creation.md

---

styles/youtube/catppuccin.user.css

https://github.com/catppuccin/userstyles/issues/358

fix(youtube): end cards

---

styles/linkedin/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/360

fix(linkedin): button colouring

---

styles/stylus/catppuccin.user.css

fix(stylus): background color when having multiple codes

---

styles/reddit/catppuccin.user.css

fix(reddit): notification icon text color

---

styles/instagram/catppuccin.user.css

The share box when sharing a post/reel.
this took way too long and i am now annoyed at instagram. Thanks lizard man for not making it easy

fix: Instagram Share box colors

---

styles/youtube/catppuccin.user.css

fix(youtube): voice color

---

styles/instagram/catppuccin.user.css

all for the style to even be used

fix(insta): usage

---

styles/youtube/catppuccin.user.css

fix(yt): match the defaults closer

---

styles/youtube/catppuccin.user.css

fix(youtube): theme the icons in the sidebar

---

styles/youtube/catppuccin.user.css

the location of the yt services are variable to change

fix(yt): the location of the yt services are variable to change

---

styles/github/catppuccin.user.css

fix(github): some unthemed elements

---

styles/tuta/catppuccin.user.css

fix(tuta): update metadata

---

.github/labels.yml
scripts/userstyles.yml
styles/lichess/catppuccin.user.css
styles/wikiwand/catppuccin.user.css

chore: properly capitalize names

---

.github/workflows/lint-build.yml

fix for failing ci https://github.com/catppuccin/userstyles/actions/workflows/lint-build.yml

fix(ci/lint-build): add GH_TOKEN to enviroment

---

styles/nixos.wiki/catppuccin.user.css

fix(nixos.wiki): search color

---

styles/lastfm/catppuccin.user.css

fix(lastfm): Style error page

---

scripts/lint/main.ts
scripts/lint/stylelint.ts

ci(lint): exit with error when issues are found

---

styles/github/catppuccin.user.css

Closes #422
https://regexr.com/7pqa8

fix(github): regex

---

styles/pinterest/catppuccin.user.css

Makes the style rely less on crappy classes, and instead uses slightly-less-crappy variables.
Increases the readability and will hopefully be more stable.
The mobile is still broken, but *only slightly* better. I will look at it later.
Also closes #393.

feat(pinterest): rewrite

---

styles/chatgpt/catppuccin.user.css

fix(chatgpt): nav bar theming

---

styles/instagram/catppuccin.user.css

allllll the toggle sliders + some accented words

feat(instagram): theme some assorted unthemed elements

---

styles/graphite/catppuccin.user.css

change meta typo
not applicable

fix(graphite): typo

---

styles/lastfm/catppuccin.user.css

- Liking a track plays the intended animation on Chrome
-  Code cleanups

fix(lastfm): fix love animation & various cleanups

---

scripts/userstyles.yml

Add more colors to the schema where appropriate.

chore: add more colors to the appropriate userstyles

---

styles/google/catppuccin.user.css

fix(google): amogus

---

styles/youtube/catppuccin.user.css

fix(youtube): Video Music Title

---

styles/google/catppuccin.user.css

fix(google): Fix more uncolored stuff

---

styles/reddit/catppuccin.user.css

fix(reddit): tag color

---

styles/lastfm/catppuccin.user.css

- fixes #463 
- themes new listening report page

fix(lastfm): Listening report page overhaul

---

styles/modrinth/catppuccin.user.css

Fixes lots of new variables and overrides the global focus outline color.

fix(modrinth): update variables and fix outline

---

styles/whatsapp-web/catppuccin.user.css

Higher contrast for `text within backticks` (as opposed to dark on dark).

fix: Improve visibility of inline code text

---

styles/reddit/catppuccin.user.css

fix(reddit): follower text color

---

template/catppuccin.user.css

darkflavor for light theme and lightflavor for dark theme!?!?!?!? Unthinkable!!

fix(template): wrong flavor for themes

---

styles/bsky/catppuccin.user.css

bluesky changed some inlined colors that the userstyle matches for, so things broke
there's probably some things that I missed, i did this as a really quick fix, will probably do a proper check later today

fix(bsky): some unthemed parts 

---

styles/ecosia/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/480

fix(ecosia): landing page numbers

---

styles/google/catppuccin.user.css

[#472](https://github.com/catppuccin/userstyles/issues/472)

fix(google): definition box text

---

styles/youtube/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/489

fix(YouTube): button hovers

---

styles/codeberg/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/493
by no means should this be a permeant fix just waiting for upstream to make a public share of the files

fix(codeberg): prevent error 404

---

styles/perplexity/catppuccin.user.css

Fixed input boxes' placeholder text and caret color. Fixed some icons on the side for search for image/video/generate image.

fix(perplexity): input box, icons, hover states

---

styles/stylus/catppuccin.user.css

fix(stylus): red color

---

scripts/userstyles.yml

I'd like to start maintaining the GitHub userstyle :)

chore(github): add uncenter to current-maintainers

---

styles/google/catppuccin.user.css

fix(google): ai search

---

styles/github/catppuccin.user.css

fix(github): user mention backgrounds and improve button styling

---

styles/github/catppuccin.user.css

Fixes a button on the new repository view, that made me realize that most of the theme can just be done with variables and so I went through all of the dead stuff near the bottom and tested it with / without. Seems to work just fine without any of it!

refactor(github): clean out unused/dead code

---

styles/youtube/catppuccin.user.css

noticed some stuff was unthemed, so i fixed it, yw bell :3

fix(youtube): buy/rent movie colors

---

styles/microsoft-word/catppuccin.user.css
styles/wikipedia/catppuccin.user.css

Based off of the information learnt from https://github.com/catppuccin/userstyles/pull/522 we still use some British spellings of flavor which we don't want to do.

fix: correct spellings of flavor

---

scripts/userstyles.yml

Updates userstyles.yml to match my current GitHub username

chore: update github username for alaidriel

---

styles/duckduckgo/catppuccin.user.css

who doesn't love searching for recipes

fix(duckduckgo): recipes

---

styles/youtube/catppuccin.user.css

fix(youtube): description (I hope this time fr)

---

styles/mdn/catppuccin.user.css

fix(mdn): add support url

---

styles/formative/catppuccin.user.css

Rewrote the theme, makes it a bit cleaner to read. Also fixed some bugs with the question elements.

fix(formative): rewrite and theme much more

---

styles/instagram/catppuccin.user.css

got an uncenter to hunt for bugs and found one
loading icon

fix(instagram): loading icon

---

styles/pinterest/catppuccin.user.css

fixes https://github.com/catppuccin/userstyles/issues/556

fix(pinstrest): assorted bugs

---

styles/chatgpt/catppuccin.user.css

fixes https://github.com/catppuccin/userstyles/issues/537

fix(chatgpt): lightness

---

styles/duckduckgo/catppuccin.user.css

while i was trying to check the weather, i found out it was not themed, and that annoyed the heck out of me, so i themed it :)

fix(duckduckgo): weather info box

---

styles/linkedin/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/563

fix(linkedin): codeblocks

---

styles/twitch/catppuccin.user.css

fix(twitch): logo + topbar shadow

---

styles/duckduckgo/catppuccin.user.css

fix(duckduckgo): region switcher button

---

scripts/userstyles.yml

Forgot to update as part of #559, sorry.

chore: update schema link

---

styles/wikipedia/catppuccin.user.css

closes #513 and themes other things too

fix(wikipedia): unthemed elements

---

styles/twitch/catppuccin.user.css

fixes https://github.com/catppuccin/userstyles/pull/581#discussion_r1507533027

fix(twitch): button text color, edit 2

---

styles/lastfm/catppuccin.user.css

- Love track animation not playing
- #551

fix(lastfm): fix #551 and love track animation

---

docs/userstyle-creation.md

Updating the docs to follow the changes made by https://github.com/catppuccin/userstyles/pull/559.

docs: multiple categories are allowed in the userstyles.yml

---

scripts/userstyles.yml
styles/libreddit/catppuccin.user.css

Add libreddit fork
closes https://github.com/catppuccin/userstyles/issues/561

chore: add libreddit fork

---

scripts/userstyles.yml

fix(redlib/libreddit): add another link

---

styles/wikipedia/catppuccin.user.css

I removed the border from code-blocks as I believe it looks better without it.

feat(wikipedia): Theme syntax highlighting, Fix line numbers in code-blocks, and stylistic changes. (#601)

---

styles/wikipedia/catppuccin.user.css

fix(wikipedia): typo

---

styles/google/catppuccin.user.css

bunch of movie related things, as per @uncenter pinging me to fix it despite me not being the maintainter :omegalul:

fix(google): bunch of movie related things

---

styles/instagram/catppuccin.user.css

what uncenter pointed out + some things that were themed wrong

fix(instagram): assorted fixes that uncenter pointed out

---

styles/lastfm/catppuccin.user.css

The dropdown menu pointer is an image, so I couldn't set a border for it and have a clean implementation.
The increment handles couldn't be themed with CSS alone as well, so I've temporarily disabled them until a solution is found.

fix(lastfm): fix #646

---

.github/labels.yml
styles/google/catppuccin.user.css

a bunch of unthemed shit, such as google travel

fix(google): a whole bunch of unthemed elements

---

scripts/generate/templates/userstyle-issue.yml

We should add a checkbox to ensure the user is using the latest version of the theme to prevent versioning issues.

chore(templates/issues): ensure that users are on the latest userstyle

---

scripts/sync-maintainers/main.ts

Fixes https://github.com/catppuccin/userstyles/actions/runs/8303078770/job/22726547302.

ci(sync-maintainers): fix accidental .catch()

---

styles/duckduckgo/catppuccin.user.css

time zone description colors + setting dropdown arrows

fix(duckduckgo): time zone colors

---

styles/lastfm/catppuccin.user.css

fix(lastfm): theme recs-feed icons

---

styles/duckduckgo/catppuccin.user.css

fix(duckduckgo): currency exchange infobox's currency selector color

---

scripts/userstyles.yml

see https://github.com/catppuccin/catppuccin/discussions/2316#discussioncomment-8891385

chore(startpage): bartlibert is now a past maintainer

---

scripts/userstyles.yml

See https://github.com/catppuccin/catppuccin/discussions/2316#discussioncomment-8891830

chore: move jn-sena to past maintainers

---

styles/github/catppuccin.user.css

Themes additional variables that I have noticed since #690.

fix(github): little things

---

styles/twitch/catppuccin.user.css

fix(twitch): hype train notifs

---

styles/twitch/catppuccin.user.css

fix(twitch): chat paused button

---

.github/workflows/website.yml

First time writing CI to call a reusable workflow, lets see if it works first try :D 
Depends on https://github.com/catppuccin/catppuccin/pull/2322

ci: add deploy website workflow

---

scripts/userstyles.yml

Latest simple-icons release has these new icons we can use :p

chore: add icons for some userstyles

---

styles/github/catppuccin.user.css

fix(github): top nav bar when logged out

---

styles/migadu-webmail/catppuccin.user.css

| --- | --- |
| ![image](https://github.com/catppuccin/userstyles/assets/47499684/40d42f4b-be20-4bbd-bc73-bfcffa081c8c) | ![image](https://github.com/catppuccin/userstyles/assets/47499684/9b53bd5f-4f6c-4819-95b1-203fa233f765) |

fix(migadu-webmail): email address field

---

styles/migadu-webmail/catppuccin.user.css

Themes checkboxes and background colors for selected contacts.

fix(migadu-webmail): selected contacts

---

styles/youtube/catppuccin.user.css

chore(yt): cleanup

---

scripts/userstyles.yml
styles/pronouns.page/catppuccin.user.css
styles/pronouns.page/preview.webp

A website for sharing and learning about pronouns & other queer vocabulary.
N/A
template.

feat(pronouns.page): init

---

styles/migadu-webmail/catppuccin.user.css

Looks like I didn't fix this properly last time :/

fix(migadu-webmail): selected emails & contacts

---

styles/wikipedia/catppuccin.user.css

fix(wikipedia): table text color on highlighted cells

---

styles/wikipedia/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/660

fix(wikipedia): maths eqations

---

styles/youtube/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/676
and some misc other changes

refactor(youtube): cleanup and misc changes

---

styles/google/catppuccin.user.css

Closes https://github.com/catppuccin/userstyles/issues/618

fix(google): fix unthemed elements

---

styles/youtube/catppuccin.user.css

correct some broken things from https://github.com/catppuccin/userstyles/pull/745

fix(yt): logo regression

---

styles/youtube/catppuccin.user.css

fix(youtube): reply buttons

---

scripts/userstyles.yml

Adds me as a maintainer to the YouTube userstyle :)

chore(youtube): add uncenter as current maintainer

---

styles/hacker-news/catppuccin.user.css

Removes large sections of CSS, simplifications.

refactor(hacker-news): semi-rewrite

---

styles/github/catppuccin.user.css

Did an oopsies in #766, reverts.

fix(github): oopsies

---

styles/reddit/catppuccin.user.css

Themes the "Reddit" text next to the logo, some stuff related to the upvote/downvote buttons, and one other button that I can't remember where it was.

fix(reddit): misc

---

styles/youtube/catppuccin.user.css

Rewrites the userstyle, 50% less lines, less crud :). Variables are kept the same for the most part, though we should try to prune those a bit. I got rid of the extra mobile styling for now but I will come back to it if needed.

refactor(youtube): rewrite

---

styles/youtube/catppuccin.user.css

Fixes these weird white corners behind the floating box containing search results, themes another instance of the live badge.

fix(youtube): search box background and magnifying icon, live badge

---

styles/youtube/catppuccin.user.css

icba. version updated, followed the guidelines, sorry for all the small patches :p

fix(youtube): description text on app light mode

---

styles/youtube/catppuccin.user.css

fix(youtube): search box in app light mode

---

styles/nextjs/catppuccin.user.css

not sure when this was introduced but yeah

fix(nextjs): syntax error

---

styles/deepl/catppuccin.user.css

https://github.com/catppuccin/userstyles/actions/runs/8637574207/job/23680055341

fix(deepl): duplicate selector

---

styles/instagram/catppuccin.user.css

fix(instagram): threads logooooo

---

docs/how-to-write-a-userstyle.md
docs/tips-and-tricks.md

docs(tips-and-tricks): add  How can I inspect hard-to-grab elements? tip

---

styles/lingva/catppuccin.user.css

fix(lingva): remove my custom instance

---

styles/lingva/catppuccin.user.css

Please go the the `Preview` tab and click on the link to the appropriate pull request template.
Are you...
- [Adding a new userstyle?](?expand=1&template=userstyle-creation.md)
- [Updating/fixing an existing userstyle?](?expand=1&template=userstyle-update.md)
- Something else? Delete this text and write a short, meaningful description of your changes instead.

fix(lingva): ruby moment

---

.github/workflows/website.yml

Prevents deploy from running in forks

ci(website): dont run on forks

---

styles/youtube/catppuccin.user.css

fix(youtube): searchbar corner for ambient mode

---

scripts/userstyles.yml

i do not use canvas anymore and cannot maintain the userstyle

chore(canvas-lms): remove TheMemeSniper from current maintainers

---

styles/youtube/catppuccin.user.css

the notification icon is not themed

fix(youtube): notification icon not themed

---

styles/youtube/catppuccin.user.css

refactor(youtube): organization

---

styles/chatgpt/catppuccin.user.css

fix(chatgpt): update domain

---

README.md

docs: use badges for stylus extension installation

---

styles/wikipedia/catppuccin.user.css

fix(wikipedia): equations and tables styling fixes 

---

scripts/userstyles.yml
styles/keyoxide/catppuccin.user.css
styles/keyoxide/preview.webp

Keyoxide is a decentralized tool to create and verify decentralized online identities.
N/A
template.

feat(keyoxide): init

---

scripts/userstyles.yml

rename amelia from `night-lake` to `nyameliaaaa`

chore: rename amelia

---

scripts/userstyles.yml

rename "Natalie Ashley Raine" to just "Natalie Raine"

chore: rename natalie

---

styles/chatgpt/catppuccin.user.css

Themes the new UI, fixes some things I didn't notice before.

feat(chatgpt): update for new ui

---

styles/twitter/catppuccin.user.css

Adds the URL x.com since the URL is being changed
Fixes the URL since it has been updated or is being updated

fix(twitter): add x.com url

---

styles/duckduckgo/catppuccin.user.css

<table>
<tr>
<td>
before
<td>
after
<tr>
<td>
<td>
</table>

fix(ddg): error displaying search results text

---

scripts/userstyles.yml
styles/crates.io/catppuccin.user.css
styles/crates.io/preview.webp

feat(crates.io): init

---

styles/twitch/catppuccin.user.css

fix(twitch): extension overlay background

---

scripts/userstyles.yml

Adds some missing icons. Waiting on https://github.com/iconify/icon-sets to update Simple Icons so that the website doesn't complain.

chore: add various missing icons

---

styles/duckduckgo/catppuccin.user.css

fixes the infobox for stocks + themes the new ai chat feature that ddg implemented

fix(duckduckgo): stocks infobox + ai chat

---

scripts/userstyles.yml

I'm better now so I'd like to keep maintaining these userstyles if that's okay.

chore(maintainers): move jn-sena to current maintainers

---

styles/formative/catppuccin.user.css

Update for some classname and practice set UI changes, theme badges

fix(formative): update for classname and practice set changes

---

scripts/sync-maintainers/main.ts

ci(sync-maintainers): hoist `current-maintainers` key

---

styles/youtube/catppuccin.user.css

fix(youtube): stats for nerds

---

scripts/userstyles.yml

chore(userstyles.yml): `andreasgrafen` -> @unseen-ninja

---

styles/duckduckgo/catppuccin.user.css

fix(duckduckgo): assorted elemets

---

deno.json
deno.lock

See https://github.com/catppuccin/catppuccin/pull/2418, fixes https://github.com/catppuccin/userstyles/actions/runs/9400652801/job/25890715440.

chore(deps): update `catppuccin/catppuccin` schema

---

styles/youtube/catppuccin.user.css

Fixes new player ui
Old
New
i know what a crazy fix

feat(youtube): new player ui

---

styles/github/preview.webp

Figured it was time to update the preview :)
| --- | --- |
| ![](https://media.githubusercontent.com/media/catppuccin/userstyles/main/styles/github/preview.webp) | ![](https://media.githubusercontent.com/media/catppuccin/userstyles/47459ef3a7237e559501a4743a82dc7dea52b769/styles/github/preview.webp) |

chore(github): update preview image

---

styles/go.dev/catppuccin.user.css

:p check logs https://github.com/catppuccin/userstyles/actions/runs/9446601389

fix(go.dev): formatter fail

---

scripts/userstyles.yml

Hey @cecelot! We noticed that your username has changed and this PR updates your information in our data file.

chore(userstyles.yml): `alythical` -> @cecelot

---

docs/CONTRIBUTING.md

Was reading this over and realized I wasn't as explicit as I thought when I originally wrote it!

docs(CONTRIBUTING.md): clean up opinionated changes wording

---

styles/codeberg/catppuccin.user.css

fix(codeberg): more conditional changes to apply patches

---

scripts/userstyles.yml

Same reasoning as https://github.com/catppuccin/catppuccin/pull/2440. Willing to keep maintaining everything else though.

chore(userstyles.yml): move myself into past-maintainers for some ports

---

styles/twitch/catppuccin.user.css

Uhh fixes a lot of things while I watched Sentinels demolish NRG in the match tonight. Fixes verified badges for organizations and streamers, changes the red accent to be the actual accent (as we do in other userstyles), themes various links, fixes logo contrast.

fix(twitch): misc

---

styles/npm/catppuccin.user.css

Fixes the profile menu dropdown not being properly selected due to a change in the HTML structure.

fix(npm): profile dropdown menu in header

---

styles/crates.io/catppuccin.user.css

Seems like the numbers for each variable drifts over time with updates so a few things became unthemed or were adjusted by the wrong variable. I've thoroughly gone through every page I can find and everything appears to now be correctly themed again.

fix(crates.io): various updated variables

---

styles/wikipedia/catppuccin.user.css

fix(wikipedia): missing specificity issues

---

styles/twitch/catppuccin.user.css

refactor(twitch): clean up unused styles, organize

---

styles/crates.io/catppuccin.user.css

Fixes the borders of tables. No variable used here for some reason.

fix(crates.io): table borders

---

scripts/userstyles.yml
styles/porkbun/catppuccin.user.css
styles/porkbun/preview.webp

feat(porkbun): init

---

styles/arch-wiki/catppuccin.user.css

i was testing out the arch wiki and i found a bunch of broken stuff
which i fixed

fix(arch-wiki): fix a bunch of broken stuff

---

styles/porkbun/catppuccin.user.css

Was buying a new domain, button looked strange and this fixes it.

fix(porkbun): active button

---

scripts/userstyles.yml

Removing myself from the chess.com maintainers list.

chore(chess.com): move coldenate to past maintainers

---

styles/npm/catppuccin.user.css

the "featured components" part is the same with the rest of the pages

feat(npm): home, products, teams, and pro pages

---

styles/mastodon/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/966

feat(mastodon): support system theme

---

styles/google-photos/catppuccin.user.css

themes the print store page, and fixes a bunch of text not being themed on various pages,

fix(google-photos): a bunch of assorted minor fixes

---

scripts/import-styles/main.ts

fix(scripts): await `@std/fs`'s `ensureDir`

---

styles/gmail/catppuccin.user.css

fix(gmail): misc

---

styles/pinterest/catppuccin.user.css

exact same thing as #1069
i couldn't reopen that pr because the branches were deleted

fix(pinterest): unthemed variables

---

styles/google/catppuccin.user.css

same exact pr as #1056
i wasn't able to reopen it because i deleted the old userstyles branches and i wasn't able to make any other one because i was banned

fix(google): unthemed background

---

styles/deepl/catppuccin.user.css

refactor(deepl): rewrite

---

styles/youtube/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/1111

fix(youtube): youtube shorts like button

---

styles/youtube/catppuccin.user.css

fix(youtube): unthemed skeleton

---

styles/youtube/catppuccin.user.css

fix(youtube): unthemed text

---

styles/deepl/catppuccin.user.css

fix(deepl): dropdown, logo, text and hover

---

styles/phanpy/catppuccin.user.css

Fixes most things on #1079
- Fix color on see more replies
- Fix color on profile sections
- Fix color on posts bar
- Fix color on focus in some elements

fix(phanpy): Fix some colors

---

docs/tips-and-tricks.md

#1141, https://github.com/catppuccin/userstyles/pull/1130#discussion_r1701745341

docs(tips-and-tricks): improve image theming tips

---

styles/youtube/catppuccin.user.css

also this is probably going to be my last PR before i stop contributing lol

fix(youtube): unthemed text and icons

---

styles/youtube/catppuccin.user.css

fix(youtube): unthemed super thanks bar

---

styles/npm/catppuccin.user.css

fix(npm): signup form text

---

styles/google/catppuccin.user.css

fix(google): unthemed section

---

styles/chess.com/catppuccin.user.css

also im going to start making PRs less so i don't make reviewing/working hard for maintaners

fix(chess.com): unthemed buttons

---

styles/youtube/catppuccin.user.css

fix(youtube): disabled buttons

---

scripts/import-styles/main.ts

fix(scripts/import-styles): disable stylelint linter in stylus editor

---

styles/stylus/catppuccin.user.css

refactor(stylus): use nesting wherever possible, simplify selectors

---

styles/duckduckgo/catppuccin.user.css

themes the rain icon as well as some text

fix(duckduckgo): weather stuff

---

styles/modrinth/catppuccin.user.css

This adds the missing variables to theme the new ui elements.
Closes #1222

fix(modrinth): add theming for new ui

---

styles/instagram/catppuccin.user.css

the notes thought bubble, the add to highlights thingy on your profile, and the close button in the search bar

fix(instagram): assorted changes

---

styles/google/catppuccin.user.css

theme several unthemed elements. i added comments on what each thing themes

fix(google): unthemed elements

---

styles/youtube/catppuccin.user.css

feat(youtube): add ambient mode for shorts

---

styles/youtube/catppuccin.user.css

fix top bar not themed under certain conditions, Closes #1219

fix(youtube): top bar header

---

styles/namemc/catppuccin.user.css

fixes the issues highlighted after #1207 was mistakenly merged

fix(namemc): requested changes

---

styles/youtube/catppuccin.user.css

fix(youtube): change 1px to 0

---

styles/github/catppuccin.user.css

Fixes incorrectly colored search icon when logged out.

fix(github): header search icon when logged out

---

styles/google/catppuccin.user.css

Fixes the search console box.
Closes #1180.
<details>
<summary>Before/After</summary>
</details>

fix(google): search console box

---

scripts/lint/file-checker.ts
scripts/lint/main.ts
scripts/lint/metadata.ts
scripts/lint/stylelint.ts
scripts/logger.ts
scripts/utils.ts

Various improvements to the logger, multiple bug fixes. Improves some specific confusing log messages, uses the logger in all places possible for consistency.

feat: improve scripts/lint logging

---

styles/crates.io/catppuccin.user.css

Fixes a unthemed button aswell as links in the wrong color.
<details>
<summary>Before & After (Outdated)</summary>
</details>

fix(crates.io): misc

---

styles/npm/catppuccin.user.css

Removes some autogenerated classes that weren't broken but could be themed other ways for clarity, some deprecation and package settings-related things are now themed,.

fix(npm): misc

---

styles/google/catppuccin.user.css

Fixes a bunch of widgets, search bars, etc
Closes #960, Closes #847 
Some widgets might not be fixed because some important parts of it are impossible to theme or its already themed.
<details>
<summary>Previews (Some screenshots might be outdated)</summary>
</details>

fix(google): misc

---

styles/linkedin/catppuccin.user.css

you're very welcome @isabelroses :)
(actually it closes #1318 lol)

fix(linkedin): invert text color

---

styles/inoreader/catppuccin.user.css

Fixes articles text color on new UI.
Add support for article progress bar

fix(inoreader): article text & progress bar

---

styles/substack/catppuccin.user.css

Giving this guy a breath of fresh air. Looks better on the few Substack pages I found, did a full sweep of the site / feed / editor and looks good to me, or certainly in a better shape than before.

refactor(substack): rewrite

---

styles/linkedin/catppuccin.user.css

fix(linkedin): editing pfp visablity on latte

---

styles/substack/catppuccin.user.css

fix(substack): misc

---

styles/lastfm/catppuccin.user.css

fix(lastfm): last.month/info banner

---

styles/modrinth/catppuccin.user.css

theme unthemed elements (especially in the landing page)

fix(modrinth): unthemed elements

---

styles/inoreader/catppuccin.user.css

Add support for new share popup menu on article.

feat(inoreader): popup menu

---

styles/google/catppuccin.user.css

fixes a bunch of bugs i found on mobile, including unthemed search suggestions, text and borders, i was able to test it by using chrome's devtools
closes #365

fix(google): mobile ui fixes

---

styles/reddit/catppuccin.user.css

fix(reddit): error text color

---

styles/youtube/catppuccin.user.css

make search suggestions lighter without changing a variable therefore not accidentally theming anything else
make player elements slightly (10%) transparent like in unthemed youtube
make the arrows in horizontal lists lighter than base
theme the unthemed sign in button

fix(youtube): unthemed elements

---

styles/duckduckgo/catppuccin.user.css

fix(duckduckgo): heading text

---

styles/chess.com/catppuccin.user.css

fix(chess.com): linter

---

styles/mastodon/catppuccin.user.css

refactors the default domains to the three provided by hammy

fix(mastodon)!: update applied domains

---

styles/chatgpt/catppuccin.user.css

closes https://github.com/catppuccin/userstyles/issues/1375

fix(chatgpt): codeblocks

---

scripts/userstyles.yml

adding myself to the maintainers list for the mastodon userstyle.

chore: add comfysage mastodon maintainer

---

styles/bsky/catppuccin.user.css

light mode is mainly untested/untouched, not fully finished yet
may have some issues because i changed a couple things quite a bit
i also want to restructure some parts of the style, but i might do that in another PR
fixes some selectors for the current bluesky web app as i haven't touched this style in like, 6 months oops lol
(mostly buttons, backgrounds, etc being broken, and a lot of selectors no longer matching anything at all)
also themes direct messages now as those didn't exist when i last touched this style

feat(bsky): update selectors for current version

---

README.md

docs: add tip for dark reader conflicts

---

docs/userstyle-creation.md

> Establish criteria for userstyle acceptance: some usage metrics, or some amount of pages that benefit significantly from having a userstyle (I don't think we really want to theme single page websites like home pages).
part of https://github.com/catppuccin/userstyles/issues/1357

docs: add minimum requirements warning for new userstyles

---

scripts/userstyles.yml

@mustafakhalaf-git can you confirm your happy with this change? or would you prefer to be removed?

chore(maintainers): remove GitMuslim

---

styles/twitch/catppuccin.user.css

fix(twitch): ffz uptime timer

---

styles/twitch/catppuccin.user.css

- Fixed unthemed hr in docs
- Fixed wrong link color in dev console
- Fixed wrong text color on hover in VOD chapters

fix(twitch): dev console, unthemed hr & vod chapters

---

scripts/userstyles.yml
styles/nixos-manual/catppuccin.user.css

fixes ci failure.
logs: https://github.com/catppuccin/userstyles/actions/runs/11934798547

fix(nixos-manual): name array

---

styles/bsky/catppuccin.user.css

fixes #1417 
| **Before**                    | **After**                 |
| ----------------------------- | ------------------------- |
| ![image](https://github.com/user-attachments/assets/bc79559b-bd92-4b9f-be59-b21c7e10e92b) | ![image](https://github.com/user-attachments/assets/aa1182d2-e1bc-440d-81d8-e4e896377025)

fix(bsky): edit profile save changes button

---

styles/twitch/catppuccin.user.css

- Fixed toggle buttons and checkboxes on latte
- Fixed player controls and overlays color on latte
- Themed announcements button in dashboard
- Themed clips watch live prompt

fix(twitch): latte & clips fixes

---

styles/youtube/catppuccin.user.css

fix(youtube): live chat replay

---

styles/github/catppuccin.user.css

closes #1333
fixes unthemed nav controls, boxes and groups of the flowchart/mermaid

fix(github): mermaid diagrams

---

renovate.json
renovate.json5

I think this works, can't be sure until its merged.

chore(renovate): disable updates for `@std`

---

docs/FAQ.md

docs(FAQ.md): remove note about why port requests need to be made where

---

docs/userstylesyml.md

Yeah this is annoying isn't it.

docs(userstylesyml.md): adjust wording to avoid prettier formatting bug

---

styles/github/catppuccin.user.css

Closes #1523, fixes another small issue I noticed.

fix(github): logged out header search placeholder text, diff hunk bg

---

styles/mastodon/catppuccin.user.css

fix https://github.com/catppuccin/userstyles/issues/1524

fix(mastodon): style buttons with `active` class

---

scripts/userstyles.yml
styles/ghostty.org/catppuccin.user.css
styles/ghostty.org/preview.webp

Currently not publicly accessible.
template.

feat(ghostty.org): init

---

docs/USAGE.md

New URL for the site, improved wording.

docs(USAGE.md): update custom userstyles import file instructions

---

.github/workflows/ci.yml

ci: auto bump changed userstyles on pr merge

---

styles/youtube/catppuccin.user.css

| --- | --- |
| ![CleanShot 2024-12-28 at 19 12 34](https://github.com/user-attachments/assets/fcb8dc65-d0c3-4df6-8018-fe64a1aa628f) | ![CleanShot 2024-12-28 at 19 12 42](https://github.com/user-attachments/assets/7cbf4e62-95f7-4977-a525-57f64810450b) |

fix(youtube): create button in header

---

deno.lock
scripts/stylus-import/main.ts

See https://github.com/openstyles/stylus/issues/1866#issuecomment-2564567687.

fix(scripts/stylus-import): add calculated digest to userstyle entries

---

scripts/userstyles.yml
styles/seventv/catppuccin.user.less

Carries over changes from #1547 that didn't make it to this new one.

refactor(seventv): cleanup

---

styles/wikipedia/catppuccin.user.less

Rewrites Wikipedia! Their new dark mode support means they finally switched to properly using vars, so this works!

refactor(wikipedia): rewrite

---

styles/hoppscotch/catppuccin.user.less

Continuation of #1448, closes #852.

fix(hoppscotch): text selection color

---

styles/youtube/catppuccin.user.less

fixes various unthemed texts related to playlists
1. [fix: playlist collapsed sidebar text](https://github.com/catppuccin/userstyles/commit/f6231a429273cfaf4cb4caa695f89230d9f303d9)
2. [fix: playlist metadata](https://github.com/catppuccin/userstyles/commit/3bc1842fa3485fd1140be284d6f992c10c93e55c)
3. [fix: playlist titles in search results](https://github.com/catppuccin/userstyles/commit/34976173500c4f6541a461941e9baa30c5d9f1c3)
4. [fix: playlist card metadata](https://github.com/catppuccin/userstyles/pull/1555/commits/f4ad01890c3ff82e94e1a57c942638333fd09cd0)
| **Before** | **After** |
|------------|-----------|
|![image](https://github.com/user-attachments/assets/fff383dd-b531-431e-b2ed-19cee05acd36)|![image](https://github.com/user-attachments/assets/738c438b-668f-48bc-b512-33de9f7fbcc …

fix(youtube): various unthemed texts related to playlists

---

styles/twitch/catppuccin.user.less

- Fixes achievement border color
- Fixes clips length text color
- Fixes collection background color
- Fixes _Account suspended or deactivated_ status banner background color
- Themes stream manager quick actions
- Themes activity feed icons
- Themes chat message highlights
- Themes chat mentions

fix(twitch): dashboard fixes

---

scripts/userstyles.yml

fix(userstyles.yml): `nyatalieeee` -> `meowcelinee`

---

styles/pronouns.page/catppuccin.user.less

Updates for recent design changes; new calendar input component, new background design (has some fancy pattern, just going with a solid color though for now), etc.

fix(pronouns.page): misc

---

styles/youtube/catppuccin.user.less

Fixes #1587
|**Default**|**Before**|**After**|
|-----------|----------|---------|
|![image](https://github.com/user-attachments/assets/0ec1dbd2-f6cf-4a77-b504-57c0ad33acf9)|![image](https://github.com/user-attachments/assets/9aee4417-5165-4b1b-b266-1d5f8446a717)|![image](https://github.com/user-attachments/assets/12c5bb14-3c08-4e5c-9575-e78dbf921773)|

fix(youtube): loop checkbox in context menu

---

styles/github/catppuccin.user.less

refactor(github): remove invalid theme warning & cleanup applicators

---

styles/modrinth/catppuccin.user.less

fix(modrinth): header sections

---

styles/brave-search/catppuccin.user.less

fix(brave-search): add variables to `.is-serp` class

---

scripts/userstyles.yml
styles/seventv/catppuccin.user.less

- Themes the 7TV [browser extension](https://chromewebstore.google.com/detail/7tv/ammjkodgmmoknidbanneddgankgfejfh) on Twitch.
- Fixes emote flags and username colors on the emote page.

feat(seventv): twitch extension

---

styles/chatgpt/catppuccin.user.less

fix(chatgpt): message input box

---

styles/snapchat-web/catppuccin.user.less

Fixes reply text background, overlay color, chat bar background color, and replay button on stories.

fix(snapchat-web): fixes unthemed elements

---

styles/crates.io/catppuccin.user.less

Seems like the names of CSS variables changed and some stuff got broken. This pull request updates them.

fix(crates.io): update css variables

---

styles/pypi/catppuccin.user.less

Fixes unstyled tables
|---|---|
|![image](https://github.com/user-attachments/assets/6f9d1946-05b8-47ae-8b64-8b40f59b8518)|![image](https://github.com/user-attachments/assets/eadd0192-ac42-4f76-99e4-b35c8ee7468d)|

fix(pypi): unstyled tables

---

styles/chatgpt/catppuccin.user.less

fix(chatgpt): temporary chat contrast

---

styles/google-photos/catppuccin.user.less

fixes the storage breakdown text, the unthemed top bar and parts of the update page

fix(google-photos): assorted fixes

---

styles/canvas-lms/catppuccin.user.less
styles/pinterest/catppuccin.user.less

Because of the failing workflow earlier these two did not get bumped yet.

chore: bump changed userstyles

---

styles/pinterest/catppuccin.user.less

- Adds missing `--color-background-box-darkwash` and `--color-icon-dark` variable.  
- Corrects `color-text-light` and `color-text-dark`.  
- Adding all searchguides new variables for colors

fix(pinterest): search guide and search suggestions

---

styles/pinterest/catppuccin.user.less

- Closes #1656 
- added `--color-background-box-dark` variable

fix(pinterest): small white rectangles & messing variable

---

styles/reddit/catppuccin.user.less

fix(reddit): comment action row color

---

styles/github/catppuccin.user.less

fixes #1675 
|---|---|
|![image](https://github.com/user-attachments/assets/89317827-6274-45e8-a6de-c3b48a642974)|![image](https://github.com/user-attachments/assets/4684c156-ca36-4d4a-a1ac-14ca7d2c6aa7)|

fix(github): contribution graph

---

styles/pinterest/catppuccin.user.less

fixing nav icons not begin themed cause of selectors changes

fix(pinterest): sidebar navigation icons

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/deno-check.yml
.github/workflows/deno-lock.yml
.github/workflows/lint.yml
.github/workflows/maintainers.yml
flake.lock

chore: update deno

---

styles/pinterest/catppuccin.user.less

fix(pinterest): pin dropdown title color

---

styles/snapchat-web/catppuccin.user.less

fix(snapchat-web): add "www" prefix

---

styles/youtube/catppuccin.user.less

the handle and pronouns in the user profile popup in the comments

fix(youtube): profile popup handle and pronouns

---

styles/youtube/catppuccin.user.less

This theme the sponsor block colors on timebar. not really sure if we should theme this as the user can set their custom colors in the SponsorBlock settings but... PR is here.
Closes #1647

feat(youtube): sponsor block elements

---

styles/youtube/catppuccin.user.less

This PR themes [Enhancer for YouTube](https://www.mrfdev.com/enhancer-for-youtube)'s toolbar:

feat(youtube): enhancer for youtube toolbar

---

styles/canvas-lms/catppuccin.user.less

- style tabs/toggle switches better
- support for the built-in equation editor
- some button fixes (e.g. on tinymce, the use webcam button on file upload, and the buttons on mobile nav menu)

fix(canvas-lms): tabs, toggles, equation editor, misc.

---

styles/canvas-lms/catppuccin.user.less

Themes the HTML elements inserted into Canvas by https://github.com/ksucpea/bettercanvas
| Before   |      After      |
|:--------:|:-------------:|
| ![image](https://github.com/user-attachments/assets/bda45dd0-c9a3-4ae6-82a1-0431053e5c35) |  ![image](https://github.com/user-attachments/assets/f7555a18-ebfb-4dbd-82cd-eacfda8ac5c5) |

feat(canvas-lms): bettercanvas elements

---

styles/wikipedia/catppuccin.user.less

fix(wikipedia): rendered math equations

---

README.md

I didn't like how the old description read. I think this captures the message better and sticks with the classic Catppuccin "soothing pastel theme" format.

docs(README.md): update short description

---

styles/youtube/catppuccin.user.less

Fixes the unthemed category tag pills
|Before|
|---|
|![image](https://github.com/user-attachments/assets/83ca0e4a-51ea-46bc-a1ee-abbd9139c362)|
|After|
|---|
|![image](https://github.com/user-attachments/assets/2a0129c9-5ee9-4e7f-8500-a71e3fe66a49)|

fix(youtube): category tag pills

---

styles/keybr.com/catppuccin.user.less

It adds stats like speed or accuracy

fix(keybr): stats color

---

scripts/userstyles.yml

see https://github.com/catppuccin/userstyles/actions/runs/16005308158/job/45150432543#step:4:1

chore(userstyles.yml): TadoTheMiner -> janTatesa

---

styles/modrinth/catppuccin.user.less

fix(modrinth): footer gradient background

---

scripts/userstyles.yml

chore(userstyles.yml): drop `isabelroses` from various userstyles

---

scripts/userstyles.yml

Add WalkQuackBack as maintainer for whatsapp-web

chore(whatsapp-web): add `WalkQuackBack` as maintainer

---

.github/workflows/docs.yml
deno.json

Fixes https://github.com/catppuccin/userstyles/actions/runs/17363410778/job/49286540316 not being able to format the docs workflow from CI.

style(ci/docs): format workflow with deno fmt

---

styles/twitch/catppuccin.user.less

fix(twitch): seekbar & chapter selector

---

scripts/userstyles.yml

Requesting to be a maintainer for the lichess userstyle.

chore(lichess): add zenoix as maintainer

---

scripts/userstyles.yml

forgot to do this last week but remembered while at work cause a colleague pointed out 'hey why are your colours different'

chore(tldraw): add `NekoDrone` as maintainer

---

styles/youtube/catppuccin.user.less

fix(youtube): video collaborator popup/dialog background
